#! /usr/bin/perl -w

###############################################################################
# generate Aux code area size (in hex format)
# 
# Usage:
#	./gen_aux_code_area_size.pl <binary>
#
#
###############################################################################
if( !defined(@ARGV) ) {
	print "Usage:\n\t ./gen_aux_code_area_size.pl <binary>\n";
	exit;
}

my $aux_header_size = 0x114;	# fix value
my $banner = 
"##############################################################################
#
# generated by script
#
##############################################################################\n";

#open BINARY, $ARGV[0] or die "($!)\n";
open BINARY, $ARGV[0] or die $banner. "Size_Of_SCS_Auxiliary_Code_Area=unknown($!)\n\n";

my $size = -s BINARY;

print $banner;
my $aux_code_area_size = $size + $aux_header_size;
# check if aux code area size too large
die "Size_Of_SCS_Auxiliary_Code_Area=overlimit(10'$aux_code_area_size)\n\n" if ($aux_code_area_size > 32*1024);

printf "Size_Of_SCS_Auxiliary_Code_Area=%08x\n\n", $aux_code_area_size;
close BINARY;

