/* DO NOT EDIT THIS FILE!!!
 * This file was automatically generated by msgbuf compiler!
 *
 * This file contains the msgbuf structure definitions associated
 * to the package nhtbsd.proto
 */

#ifndef __MSGBUF_EXPORT_NHTBSD_H_
#define __MSGBUF_EXPORT_NHTBSD_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*****************************************************************************
 * include files                                                             *
 ****************************************************************************/


#include "inc/xsd-c.h"
#include "src/msgbuf_nhtbsd.h"



/*****************************************************************************
 * message descriptor prototype                                              *
 ****************************************************************************/

extern const TMsgBuf_messageDescriptor g_Nhtbsd_EmptyMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_BsdStatusOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_OptOutput1InMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_StringInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_StringOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_String4OutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_VersionRevisionOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_NumberOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_SizeInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_BytesOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_BytesInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_CheckNumberBytesInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_HandleOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_HandleInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_EncryptFlashProtKeyInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_ClearTextKeyInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_Level2ProtectedKeyInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_FlashProtectingKeyInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_CertKeyInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_R2rCipherInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_R2rLegacyOperationInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_RsaPublicEncryptInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_RsaPublicDecryptInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_ShaUpdateInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_ShaTerminateInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_HmacShaInitInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_RandomInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtbsd_R2rMonteCarloParamsInMsg_messageDescriptor;

/*****************************************************************************
 * enum descriptor prototype                                                 *
 ****************************************************************************/


/*****************************************************************************
 * service descriptor prototype                                              *
 ****************************************************************************/

extern const TMsgBuf_serviceDescriptor g_nhtbsd_v2_0_4_serviceDescriptor;

#ifdef __cplusplus
}
#endif /* __cplusplus */


#endif /* __MSGBUF_EXPORT_NHTBSD_H_ */
