/* DO NOT EDIT THIS FILE!!!
 * This file was automatically generated by msgbuf compiler!
 *
 * This file contains the msgbuf structure definitions associated
 * to the package nhtbsd.proto
 */


/*****************************************************************************
 * include files                                                             *
 ****************************************************************************/

#include "inc/rpc_nhtbsd.h"
#include "src/rpc_nhtbsd_api.h"
#include "src/_msgbuf_nhtbsd.h"



/*****************************************************************************
 * RPC service remote API implementation                                     *
 ****************************************************************************/

