/* DO NOT EDIT THIS FILE!!!
 * This file was automatically generated by msgbuf compiler!
 *
 * This file contains the msgbuf structure definitions associated
 * to the package nhtreport.proto
 */

#ifndef __MSGBUF_EXPORT_NHTREPORT_H_
#define __MSGBUF_EXPORT_NHTREPORT_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*****************************************************************************
 * include files                                                             *
 ****************************************************************************/


#include "inc/xsd-c.h"
#include "src/msgbuf_nhtreport.h"



/*****************************************************************************
 * message descriptor prototype                                              *
 ****************************************************************************/

extern const TMsgBuf_messageDescriptor g_Nhtreport_ReportErrorInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtreport_ReportTraceInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtreport_ReportInfoInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtreport_EmptyMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtreport_SizeInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtreport_GetSizeInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtreport_ReportFTraceInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtreport_ReportTextInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtreport_ReportTextOutMsg_messageDescriptor;

/*****************************************************************************
 * enum descriptor prototype                                                 *
 ****************************************************************************/


/*****************************************************************************
 * service descriptor prototype                                              *
 ****************************************************************************/

extern const TMsgBuf_serviceDescriptor g_nhtreport_v1_2_0_serviceDescriptor;

#ifdef __cplusplus
}
#endif /* __cplusplus */


#endif /* __MSGBUF_EXPORT_NHTREPORT_H_ */
