/* DO NOT EDIT THIS FILE!!!
 * This file was automatically generated by msgbuf compiler!
 *
 * This file contains the msgbuf structure definitions associated
 * to the package nhtreport.proto
 */


/*****************************************************************************
 * include files                                                             *
 ****************************************************************************/

#include "inc/msgbuf_sys_malloc.h"
#include <stddef.h>
#include "src/msgbuf_nhtreport.h"
#include "inc/rpc_nhtreport.h"
#include "src/_msgbuf_nhtreport.h"
#include "src/rpc_nhtreport_api.h"


/*****************************************************************************
 * public rpc service handle                                                 *
 ****************************************************************************/

const TMsgBuf_serviceHandle gRpcServiceHandle_nhtreport = (TMsgBuf_serviceHandle)&g_nhtreport_v1_2_0_serviceDescriptor;


/*****************************************************************************
 * nested message descriptor prototype                                       *
 ****************************************************************************/


/*****************************************************************************
 * Generate default value implementation                                     *
 ****************************************************************************/


/*****************************************************************************
 * enum descriptor implementation                                            *
 ****************************************************************************/


/*****************************************************************************
 * message descriptor static init implementation                             *
 ****************************************************************************/

/* Default "TNhtreport_ReportErrorInMsg" structure init value */
static const TNhtreport_ReportErrorInMsg g_reportError_inMsg_default_value =
{
  (TMsgBuf_desc)&g_Nhtreport_ReportErrorInMsg_messageDescriptor,/* Base msg descriptor ref */
  0,                                                 /* field: required uint32_t errorType   */
  0,                                                 /* field: required uint32_t errorNumber */
  NULL,                                              /* field: optional char     context     */
  NULL                                               /* field: optional char     description */
};

/* Default "TNhtreport_ReportTraceInMsg" structure init value */
static const TNhtreport_ReportTraceInMsg g_reportTrace_inMsg_default_value =
{
  (TMsgBuf_desc)&g_Nhtreport_ReportTraceInMsg_messageDescriptor,/* Base msg descriptor ref */
  0,                                                 /* field: required uint32_t errorType   */
  NULL,                                              /* field: optional char     filename    */
  0,                                                 /* field: required uint32_t line        */
  NULL,                                              /* field: optional char     context     */
  NULL                                               /* field: optional char     description */
};

/* Default "TNhtreport_ReportInfoInMsg" structure init value */
static const TNhtreport_ReportInfoInMsg g_reportInfo_inMsg_default_value =
{
  (TMsgBuf_desc)&g_Nhtreport_ReportInfoInMsg_messageDescriptor,/* Base msg descriptor ref */
  0,                                                /* field: required uint32_t errorType   */
  NULL,                                             /* field: optional char     context     */
  NULL                                              /* field: optional char     description */
};

/* Default "TNhtreport_EmptyMsg" structure init value */
static const TNhtreport_EmptyMsg g_empty_msg_default_value =
{
  (TMsgBuf_desc)&g_Nhtreport_EmptyMsg_messageDescriptor,/* Base msg descriptor ref */
};

/* Default "TNhtreport_SizeInMsg" structure init value */
static const TNhtreport_SizeInMsg g_size_inMsg_default_value =
{
  (TMsgBuf_desc)&g_Nhtreport_SizeInMsg_messageDescriptor,/* Base msg descriptor ref */
  0                                           /* field: required uint32_t value */
};

/* Default "TNhtreport_GetSizeInMsg" structure init value */
static const TNhtreport_GetSizeInMsg g_getSize_inMsg_default_value =
{
  (TMsgBuf_desc)&g_Nhtreport_GetSizeInMsg_messageDescriptor,/* Base msg descriptor ref */
  0,                                             /* field: required uint32_t     value      */
  0                                              /* field: required TMsgBuf_bool has_output */
};

/* Default "TNhtreport_ReportFTraceInMsg" structure init value */
static const TNhtreport_ReportFTraceInMsg g_reportFTrace_inMsg_default_value =
{
  (TMsgBuf_desc)&g_Nhtreport_ReportFTraceInMsg_messageDescriptor,/* Base msg descriptor ref */
  0,                                                  /* field: required uint32_t callId */
  0,                                                  /* field: required uint32_t type   */
  NULL                                                /* field: optional char     text   */
};

/* Default "TNhtreport_ReportTextInMsg" structure init value */
static const TNhtreport_ReportTextInMsg g_reportText_inMsg_default_value =
{
  (TMsgBuf_desc)&g_Nhtreport_ReportTextInMsg_messageDescriptor,/* Base msg descriptor ref */
  NULL                                              /* field: optional char text */
};

/* Default "TNhtreport_ReportTextOutMsg" structure init value */
static const TNhtreport_ReportTextOutMsg g_reportText_outMsg_default_value =
{
  (TMsgBuf_desc)&g_Nhtreport_ReportTextOutMsg_messageDescriptor,/* Base msg descriptor ref */
  NULL                                               /* field: optional char text */
};


/*****************************************************************************
 * message descriptor implementation                                         *
 ****************************************************************************/

/* "gNhtreport_ReportErrorInMsg_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Nhtreport_ReportErrorInMsg_methodsDescriptor[4] =
{
  {
    "errorType",                                             /* field: * pName */
    MSGBUF_FIELDTYPE_UINT32,                                 /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                                /* field:   label */
    0,                                                       /* field:   packed */
    1,                                                       /* field:   id */
    sizeof(uint32_t ),                                       /* field:   sizeof_field */
    0,                                                       /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtreport_ReportErrorInMsg,errorType), /* field:   offset */
    NULL,                                                    /* field: * pDescriptor */
    NULL                                                     /* field: * pDefaultValue */
  },
  {
    "errorNumber",                                             /* field: * pName */
    MSGBUF_FIELDTYPE_UINT32,                                   /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                                  /* field:   label */
    0,                                                         /* field:   packed */
    2,                                                         /* field:   id */
    sizeof(uint32_t ),                                         /* field:   sizeof_field */
    0,                                                         /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtreport_ReportErrorInMsg,errorNumber), /* field:   offset */
    NULL,                                                      /* field: * pDescriptor */
    NULL                                                       /* field: * pDefaultValue */
  },
  {
    "context",                                             /* field: * pName */
    MSGBUF_FIELDTYPE_STRING,                               /* field:   type */
    MSGBUF_TAGLABEL_OPTIONAL,                              /* field:   label */
    0,                                                     /* field:   packed */
    3,                                                     /* field:   id */
    sizeof(char*),                                         /* field:   sizeof_field */
    0,                                                     /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtreport_ReportErrorInMsg,context), /* field:   offset */
    NULL,                                                  /* field: * pDescriptor */
    NULL                                                   /* field: * pDefaultValue */
  },
  {
    "description",                                             /* field: * pName */
    MSGBUF_FIELDTYPE_STRING,                                   /* field:   type */
    MSGBUF_TAGLABEL_OPTIONAL,                                  /* field:   label */
    0,                                                         /* field:   packed */
    4,                                                         /* field:   id */
    sizeof(char*),                                             /* field:   sizeof_field */
    0,                                                         /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtreport_ReportErrorInMsg,description), /* field:   offset */
    NULL,                                                      /* field: * pDescriptor */
    NULL                                                       /* field: * pDefaultValue */
  }
};

/* "g_Nhtreport_ReportErrorInMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtreport_ReportErrorInMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,               /* field:   magicId */
  "Nhtreport_ReportErrorInMsg",                     /* field: * pName */
  "ReportErrorInMsg",                               /* field: * pShortName */
  "Nhtreport_ReportErrorInMsg",                     /* field: * c_name */
  "nhtreport",                                      /* field: * pPackageName */
  sizeof(TNhtreport_ReportErrorInMsg),              /* field:   sizeof_message */
  &g_reportError_inMsg_default_value,               /* field:   init value */
  4,                                                /* field:   n_fields */
  g_Nhtreport_ReportErrorInMsg_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                       /* field:   message_init */
};

/* "gNhtreport_ReportTraceInMsg_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Nhtreport_ReportTraceInMsg_methodsDescriptor[5] =
{
  {
    "errorType",                                             /* field: * pName */
    MSGBUF_FIELDTYPE_UINT32,                                 /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                                /* field:   label */
    0,                                                       /* field:   packed */
    1,                                                       /* field:   id */
    sizeof(uint32_t ),                                       /* field:   sizeof_field */
    0,                                                       /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtreport_ReportTraceInMsg,errorType), /* field:   offset */
    NULL,                                                    /* field: * pDescriptor */
    NULL                                                     /* field: * pDefaultValue */
  },
  {
    "filename",                                             /* field: * pName */
    MSGBUF_FIELDTYPE_STRING,                                /* field:   type */
    MSGBUF_TAGLABEL_OPTIONAL,                               /* field:   label */
    0,                                                      /* field:   packed */
    2,                                                      /* field:   id */
    sizeof(char*),                                          /* field:   sizeof_field */
    0,                                                      /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtreport_ReportTraceInMsg,filename), /* field:   offset */
    NULL,                                                   /* field: * pDescriptor */
    NULL                                                    /* field: * pDefaultValue */
  },
  {
    "line",                                             /* field: * pName */
    MSGBUF_FIELDTYPE_UINT32,                            /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                           /* field:   label */
    0,                                                  /* field:   packed */
    3,                                                  /* field:   id */
    sizeof(uint32_t ),                                  /* field:   sizeof_field */
    0,                                                  /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtreport_ReportTraceInMsg,line), /* field:   offset */
    NULL,                                               /* field: * pDescriptor */
    NULL                                                /* field: * pDefaultValue */
  },
  {
    "context",                                             /* field: * pName */
    MSGBUF_FIELDTYPE_STRING,                               /* field:   type */
    MSGBUF_TAGLABEL_OPTIONAL,                              /* field:   label */
    0,                                                     /* field:   packed */
    4,                                                     /* field:   id */
    sizeof(char*),                                         /* field:   sizeof_field */
    0,                                                     /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtreport_ReportTraceInMsg,context), /* field:   offset */
    NULL,                                                  /* field: * pDescriptor */
    NULL                                                   /* field: * pDefaultValue */
  },
  {
    "description",                                             /* field: * pName */
    MSGBUF_FIELDTYPE_STRING,                                   /* field:   type */
    MSGBUF_TAGLABEL_OPTIONAL,                                  /* field:   label */
    0,                                                         /* field:   packed */
    5,                                                         /* field:   id */
    sizeof(char*),                                             /* field:   sizeof_field */
    0,                                                         /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtreport_ReportTraceInMsg,description), /* field:   offset */
    NULL,                                                      /* field: * pDescriptor */
    NULL                                                       /* field: * pDefaultValue */
  }
};

/* "g_Nhtreport_ReportTraceInMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtreport_ReportTraceInMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,               /* field:   magicId */
  "Nhtreport_ReportTraceInMsg",                     /* field: * pName */
  "ReportTraceInMsg",                               /* field: * pShortName */
  "Nhtreport_ReportTraceInMsg",                     /* field: * c_name */
  "nhtreport",                                      /* field: * pPackageName */
  sizeof(TNhtreport_ReportTraceInMsg),              /* field:   sizeof_message */
  &g_reportTrace_inMsg_default_value,               /* field:   init value */
  5,                                                /* field:   n_fields */
  g_Nhtreport_ReportTraceInMsg_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                       /* field:   message_init */
};

/* "gNhtreport_ReportInfoInMsg_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Nhtreport_ReportInfoInMsg_methodsDescriptor[3] =
{
  {
    "errorType",                                            /* field: * pName */
    MSGBUF_FIELDTYPE_UINT32,                                /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                               /* field:   label */
    0,                                                      /* field:   packed */
    1,                                                      /* field:   id */
    sizeof(uint32_t ),                                      /* field:   sizeof_field */
    0,                                                      /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtreport_ReportInfoInMsg,errorType), /* field:   offset */
    NULL,                                                   /* field: * pDescriptor */
    NULL                                                    /* field: * pDefaultValue */
  },
  {
    "context",                                            /* field: * pName */
    MSGBUF_FIELDTYPE_STRING,                              /* field:   type */
    MSGBUF_TAGLABEL_OPTIONAL,                             /* field:   label */
    0,                                                    /* field:   packed */
    2,                                                    /* field:   id */
    sizeof(char*),                                        /* field:   sizeof_field */
    0,                                                    /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtreport_ReportInfoInMsg,context), /* field:   offset */
    NULL,                                                 /* field: * pDescriptor */
    NULL                                                  /* field: * pDefaultValue */
  },
  {
    "description",                                            /* field: * pName */
    MSGBUF_FIELDTYPE_STRING,                                  /* field:   type */
    MSGBUF_TAGLABEL_OPTIONAL,                                 /* field:   label */
    0,                                                        /* field:   packed */
    3,                                                        /* field:   id */
    sizeof(char*),                                            /* field:   sizeof_field */
    0,                                                        /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtreport_ReportInfoInMsg,description), /* field:   offset */
    NULL,                                                     /* field: * pDescriptor */
    NULL                                                      /* field: * pDefaultValue */
  }
};

/* "g_Nhtreport_ReportInfoInMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtreport_ReportInfoInMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,              /* field:   magicId */
  "Nhtreport_ReportInfoInMsg",                     /* field: * pName */
  "ReportInfoInMsg",                               /* field: * pShortName */
  "Nhtreport_ReportInfoInMsg",                     /* field: * c_name */
  "nhtreport",                                     /* field: * pPackageName */
  sizeof(TNhtreport_ReportInfoInMsg),              /* field:   sizeof_message */
  &g_reportInfo_inMsg_default_value,               /* field:   init value */
  3,                                               /* field:   n_fields */
  g_Nhtreport_ReportInfoInMsg_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                      /* field:   message_init */
};

/* "g_Nhtreport_EmptyMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtreport_EmptyMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,       /* field:   magicId */
  "Nhtreport_EmptyMsg",                     /* field: * pName */
  "EmptyMsg",                               /* field: * pShortName */
  "Nhtreport_EmptyMsg",                     /* field: * c_name */
  "nhtreport",                              /* field: * pPackageName */
  sizeof(TNhtreport_EmptyMsg),              /* field:   sizeof_message */
  &g_empty_msg_default_value,               /* field:   init value */
  0,                                        /* field:   n_fields */
  NULL,                                     /* field: * pFields */
  &msgbuf_genericMessageInit,               /* field:   message_init */
};

/* "gNhtreport_SizeInMsg_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Nhtreport_SizeInMsg_methodsDescriptor[1] =
{
  {
    "value",                                      /* field: * pName */
    MSGBUF_FIELDTYPE_UINT32,                      /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                     /* field:   label */
    0,                                            /* field:   packed */
    1,                                            /* field:   id */
    sizeof(uint32_t ),                            /* field:   sizeof_field */
    0,                                            /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtreport_SizeInMsg,value), /* field:   offset */
    NULL,                                         /* field: * pDescriptor */
    NULL                                          /* field: * pDefaultValue */
  }
};

/* "g_Nhtreport_SizeInMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtreport_SizeInMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,        /* field:   magicId */
  "Nhtreport_SizeInMsg",                     /* field: * pName */
  "SizeInMsg",                               /* field: * pShortName */
  "Nhtreport_SizeInMsg",                     /* field: * c_name */
  "nhtreport",                               /* field: * pPackageName */
  sizeof(TNhtreport_SizeInMsg),              /* field:   sizeof_message */
  &g_size_inMsg_default_value,               /* field:   init value */
  1,                                         /* field:   n_fields */
  g_Nhtreport_SizeInMsg_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                /* field:   message_init */
};

/* "gNhtreport_GetSizeInMsg_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Nhtreport_GetSizeInMsg_methodsDescriptor[2] =
{
  {
    "value",                                         /* field: * pName */
    MSGBUF_FIELDTYPE_UINT32,                         /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                        /* field:   label */
    0,                                               /* field:   packed */
    1,                                               /* field:   id */
    sizeof(uint32_t ),                               /* field:   sizeof_field */
    0,                                               /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtreport_GetSizeInMsg,value), /* field:   offset */
    NULL,                                            /* field: * pDescriptor */
    NULL                                             /* field: * pDefaultValue */
  },
  {
    "has_output",                                         /* field: * pName */
    MSGBUF_FIELDTYPE_BOOL,                                /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                             /* field:   label */
    0,                                                    /* field:   packed */
    2,                                                    /* field:   id */
    sizeof(TMsgBuf_bool ),                                /* field:   sizeof_field */
    0,                                                    /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtreport_GetSizeInMsg,has_output), /* field:   offset */
    NULL,                                                 /* field: * pDescriptor */
    NULL                                                  /* field: * pDefaultValue */
  }
};

/* "g_Nhtreport_GetSizeInMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtreport_GetSizeInMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,           /* field:   magicId */
  "Nhtreport_GetSizeInMsg",                     /* field: * pName */
  "GetSizeInMsg",                               /* field: * pShortName */
  "Nhtreport_GetSizeInMsg",                     /* field: * c_name */
  "nhtreport",                                  /* field: * pPackageName */
  sizeof(TNhtreport_GetSizeInMsg),              /* field:   sizeof_message */
  &g_getSize_inMsg_default_value,               /* field:   init value */
  2,                                            /* field:   n_fields */
  g_Nhtreport_GetSizeInMsg_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                   /* field:   message_init */
};

/* "gNhtreport_ReportFTraceInMsg_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Nhtreport_ReportFTraceInMsg_methodsDescriptor[3] =
{
  {
    "callId",                                              /* field: * pName */
    MSGBUF_FIELDTYPE_UINT32,                               /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                              /* field:   label */
    0,                                                     /* field:   packed */
    1,                                                     /* field:   id */
    sizeof(uint32_t ),                                     /* field:   sizeof_field */
    0,                                                     /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtreport_ReportFTraceInMsg,callId), /* field:   offset */
    NULL,                                                  /* field: * pDescriptor */
    NULL                                                   /* field: * pDefaultValue */
  },
  {
    "type",                                              /* field: * pName */
    MSGBUF_FIELDTYPE_UINT32,                             /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                            /* field:   label */
    0,                                                   /* field:   packed */
    2,                                                   /* field:   id */
    sizeof(uint32_t ),                                   /* field:   sizeof_field */
    0,                                                   /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtreport_ReportFTraceInMsg,type), /* field:   offset */
    NULL,                                                /* field: * pDescriptor */
    NULL                                                 /* field: * pDefaultValue */
  },
  {
    "text",                                              /* field: * pName */
    MSGBUF_FIELDTYPE_STRING,                             /* field:   type */
    MSGBUF_TAGLABEL_OPTIONAL,                            /* field:   label */
    0,                                                   /* field:   packed */
    3,                                                   /* field:   id */
    sizeof(char*),                                       /* field:   sizeof_field */
    0,                                                   /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtreport_ReportFTraceInMsg,text), /* field:   offset */
    NULL,                                                /* field: * pDescriptor */
    NULL                                                 /* field: * pDefaultValue */
  }
};

/* "g_Nhtreport_ReportFTraceInMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtreport_ReportFTraceInMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,                /* field:   magicId */
  "Nhtreport_ReportFTraceInMsg",                     /* field: * pName */
  "ReportFTraceInMsg",                               /* field: * pShortName */
  "Nhtreport_ReportFTraceInMsg",                     /* field: * c_name */
  "nhtreport",                                       /* field: * pPackageName */
  sizeof(TNhtreport_ReportFTraceInMsg),              /* field:   sizeof_message */
  &g_reportFTrace_inMsg_default_value,               /* field:   init value */
  3,                                                 /* field:   n_fields */
  g_Nhtreport_ReportFTraceInMsg_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                        /* field:   message_init */
};

/* "gNhtreport_ReportTextInMsg_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Nhtreport_ReportTextInMsg_methodsDescriptor[1] =
{
  {
    "text",                                            /* field: * pName */
    MSGBUF_FIELDTYPE_STRING,                           /* field:   type */
    MSGBUF_TAGLABEL_OPTIONAL,                          /* field:   label */
    0,                                                 /* field:   packed */
    1,                                                 /* field:   id */
    sizeof(char*),                                     /* field:   sizeof_field */
    0,                                                 /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtreport_ReportTextInMsg,text), /* field:   offset */
    NULL,                                              /* field: * pDescriptor */
    NULL                                               /* field: * pDefaultValue */
  }
};

/* "g_Nhtreport_ReportTextInMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtreport_ReportTextInMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,              /* field:   magicId */
  "Nhtreport_ReportTextInMsg",                     /* field: * pName */
  "ReportTextInMsg",                               /* field: * pShortName */
  "Nhtreport_ReportTextInMsg",                     /* field: * c_name */
  "nhtreport",                                     /* field: * pPackageName */
  sizeof(TNhtreport_ReportTextInMsg),              /* field:   sizeof_message */
  &g_reportText_inMsg_default_value,               /* field:   init value */
  1,                                               /* field:   n_fields */
  g_Nhtreport_ReportTextInMsg_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                      /* field:   message_init */
};

/* "gNhtreport_ReportTextOutMsg_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Nhtreport_ReportTextOutMsg_methodsDescriptor[1] =
{
  {
    "text",                                             /* field: * pName */
    MSGBUF_FIELDTYPE_STRING,                            /* field:   type */
    MSGBUF_TAGLABEL_OPTIONAL,                           /* field:   label */
    0,                                                  /* field:   packed */
    1,                                                  /* field:   id */
    sizeof(char*),                                      /* field:   sizeof_field */
    0,                                                  /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtreport_ReportTextOutMsg,text), /* field:   offset */
    NULL,                                               /* field: * pDescriptor */
    NULL                                                /* field: * pDefaultValue */
  }
};

/* "g_Nhtreport_ReportTextOutMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtreport_ReportTextOutMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,               /* field:   magicId */
  "Nhtreport_ReportTextOutMsg",                     /* field: * pName */
  "ReportTextOutMsg",                               /* field: * pShortName */
  "Nhtreport_ReportTextOutMsg",                     /* field: * c_name */
  "nhtreport",                                      /* field: * pPackageName */
  sizeof(TNhtreport_ReportTextOutMsg),              /* field:   sizeof_message */
  &g_reportText_outMsg_default_value,               /* field:   init value */
  1,                                                /* field:   n_fields */
  g_Nhtreport_ReportTextOutMsg_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                       /* field:   message_init */
};


/*****************************************************************************
 * message init implementation                                               *
 ****************************************************************************/

/* init_Nhtreport_ReportErrorInMsg function implementation */
void init_Nhtreport_ReportErrorInMsg ( TNhtreport_ReportErrorInMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtreport_ReportErrorInMsg_messageDescriptor); }

/* init_Nhtreport_ReportTraceInMsg function implementation */
void init_Nhtreport_ReportTraceInMsg ( TNhtreport_ReportTraceInMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtreport_ReportTraceInMsg_messageDescriptor); }

/* init_Nhtreport_ReportInfoInMsg function implementation */
void init_Nhtreport_ReportInfoInMsg ( TNhtreport_ReportInfoInMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtreport_ReportInfoInMsg_messageDescriptor); }

/* init_Nhtreport_EmptyMsg function implementation */
void init_Nhtreport_EmptyMsg ( TNhtreport_EmptyMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtreport_EmptyMsg_messageDescriptor); }

/* init_Nhtreport_SizeInMsg function implementation */
void init_Nhtreport_SizeInMsg ( TNhtreport_SizeInMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtreport_SizeInMsg_messageDescriptor); }

/* init_Nhtreport_GetSizeInMsg function implementation */
void init_Nhtreport_GetSizeInMsg ( TNhtreport_GetSizeInMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtreport_GetSizeInMsg_messageDescriptor); }

/* init_Nhtreport_ReportFTraceInMsg function implementation */
void init_Nhtreport_ReportFTraceInMsg ( TNhtreport_ReportFTraceInMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtreport_ReportFTraceInMsg_messageDescriptor); }

/* init_Nhtreport_ReportTextInMsg function implementation */
void init_Nhtreport_ReportTextInMsg ( TNhtreport_ReportTextInMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtreport_ReportTextInMsg_messageDescriptor); }

/* init_Nhtreport_ReportTextOutMsg function implementation */
void init_Nhtreport_ReportTextOutMsg ( TNhtreport_ReportTextOutMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtreport_ReportTextOutMsg_messageDescriptor); }


/*****************************************************************************
 * message alloc implementation                                              *
 ****************************************************************************/

/* pAlloc_Nhtreport_ReportErrorInMsg function implementation */
TNhtreport_ReportErrorInMsg * pAlloc_Nhtreport_ReportErrorInMsg ()
{
  TNhtreport_ReportErrorInMsg * pNewInstance;
  pNewInstance = (TNhtreport_ReportErrorInMsg*)MSGBUF_SYS_malloc(sizeof(TNhtreport_ReportErrorInMsg));
  init_Nhtreport_ReportErrorInMsg (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Nhtreport_ReportTraceInMsg function implementation */
TNhtreport_ReportTraceInMsg * pAlloc_Nhtreport_ReportTraceInMsg ()
{
  TNhtreport_ReportTraceInMsg * pNewInstance;
  pNewInstance = (TNhtreport_ReportTraceInMsg*)MSGBUF_SYS_malloc(sizeof(TNhtreport_ReportTraceInMsg));
  init_Nhtreport_ReportTraceInMsg (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Nhtreport_ReportInfoInMsg function implementation */
TNhtreport_ReportInfoInMsg * pAlloc_Nhtreport_ReportInfoInMsg ()
{
  TNhtreport_ReportInfoInMsg * pNewInstance;
  pNewInstance = (TNhtreport_ReportInfoInMsg*)MSGBUF_SYS_malloc(sizeof(TNhtreport_ReportInfoInMsg));
  init_Nhtreport_ReportInfoInMsg (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Nhtreport_EmptyMsg function implementation */
TNhtreport_EmptyMsg * pAlloc_Nhtreport_EmptyMsg ()
{
  TNhtreport_EmptyMsg * pNewInstance;
  pNewInstance = (TNhtreport_EmptyMsg*)MSGBUF_SYS_malloc(sizeof(TNhtreport_EmptyMsg));
  init_Nhtreport_EmptyMsg (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Nhtreport_SizeInMsg function implementation */
TNhtreport_SizeInMsg * pAlloc_Nhtreport_SizeInMsg ()
{
  TNhtreport_SizeInMsg * pNewInstance;
  pNewInstance = (TNhtreport_SizeInMsg*)MSGBUF_SYS_malloc(sizeof(TNhtreport_SizeInMsg));
  init_Nhtreport_SizeInMsg (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Nhtreport_GetSizeInMsg function implementation */
TNhtreport_GetSizeInMsg * pAlloc_Nhtreport_GetSizeInMsg ()
{
  TNhtreport_GetSizeInMsg * pNewInstance;
  pNewInstance = (TNhtreport_GetSizeInMsg*)MSGBUF_SYS_malloc(sizeof(TNhtreport_GetSizeInMsg));
  init_Nhtreport_GetSizeInMsg (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Nhtreport_ReportFTraceInMsg function implementation */
TNhtreport_ReportFTraceInMsg * pAlloc_Nhtreport_ReportFTraceInMsg ()
{
  TNhtreport_ReportFTraceInMsg * pNewInstance;
  pNewInstance = (TNhtreport_ReportFTraceInMsg*)MSGBUF_SYS_malloc(sizeof(TNhtreport_ReportFTraceInMsg));
  init_Nhtreport_ReportFTraceInMsg (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Nhtreport_ReportTextInMsg function implementation */
TNhtreport_ReportTextInMsg * pAlloc_Nhtreport_ReportTextInMsg ()
{
  TNhtreport_ReportTextInMsg * pNewInstance;
  pNewInstance = (TNhtreport_ReportTextInMsg*)MSGBUF_SYS_malloc(sizeof(TNhtreport_ReportTextInMsg));
  init_Nhtreport_ReportTextInMsg (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Nhtreport_ReportTextOutMsg function implementation */
TNhtreport_ReportTextOutMsg * pAlloc_Nhtreport_ReportTextOutMsg ()
{
  TNhtreport_ReportTextOutMsg * pNewInstance;
  pNewInstance = (TNhtreport_ReportTextOutMsg*)MSGBUF_SYS_malloc(sizeof(TNhtreport_ReportTextOutMsg));
  init_Nhtreport_ReportTextOutMsg (pNewInstance);
  return pNewInstance;
}


/*****************************************************************************
 * message dealloc implementation                                            *
 ****************************************************************************/

/* dealloc_Nhtreport_ReportErrorInMsg function implementation */
void dealloc_Nhtreport_ReportErrorInMsg (TNhtreport_ReportErrorInMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Nhtreport_ReportTraceInMsg function implementation */
void dealloc_Nhtreport_ReportTraceInMsg (TNhtreport_ReportTraceInMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Nhtreport_ReportInfoInMsg function implementation */
void dealloc_Nhtreport_ReportInfoInMsg (TNhtreport_ReportInfoInMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Nhtreport_EmptyMsg function implementation */
void dealloc_Nhtreport_EmptyMsg (TNhtreport_EmptyMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Nhtreport_SizeInMsg function implementation */
void dealloc_Nhtreport_SizeInMsg (TNhtreport_SizeInMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Nhtreport_GetSizeInMsg function implementation */
void dealloc_Nhtreport_GetSizeInMsg (TNhtreport_GetSizeInMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Nhtreport_ReportFTraceInMsg function implementation */
void dealloc_Nhtreport_ReportFTraceInMsg (TNhtreport_ReportFTraceInMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Nhtreport_ReportTextInMsg function implementation */
void dealloc_Nhtreport_ReportTextInMsg (TNhtreport_ReportTextInMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Nhtreport_ReportTextOutMsg function implementation */
void dealloc_Nhtreport_ReportTextOutMsg (TNhtreport_ReportTextOutMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }


/*****************************************************************************
 * msgbuf enum test function implementation                                  *
 ****************************************************************************/


/*****************************************************************************
 * service descriptor implementation                                         *
 ****************************************************************************/

static const TMsgBuf_methodDescriptor g_nhtreport_v1_2_0_serviceMethodsDescriptor[12] =
{
  /* 'tn_report_error' method descriptor (index=0) */
  {
    "tn_report_error",
    &g_Nhtreport_ReportErrorInMsg_messageDescriptor,
    &g_Nhtreport_EmptyMsg_messageDescriptor,
    (TMsgBuf_rpcFctEntry)&rpc_nhtreport_tn_report_error
  },
  /* 'tn_report_trace' method descriptor (index=1) */
  {
    "tn_report_trace",
    &g_Nhtreport_ReportTraceInMsg_messageDescriptor,
    &g_Nhtreport_EmptyMsg_messageDescriptor,
    (TMsgBuf_rpcFctEntry)&rpc_nhtreport_tn_report_trace
  },
  /* 'tn_report_info' method descriptor (index=2) */
  {
    "tn_report_info",
    &g_Nhtreport_ReportInfoInMsg_messageDescriptor,
    &g_Nhtreport_EmptyMsg_messageDescriptor,
    (TMsgBuf_rpcFctEntry)&rpc_nhtreport_tn_report_info
  },
  /* 'hc_nht_setReportLevel' method descriptor (index=3) */
  {
    "hc_nht_setReportLevel",
    &g_Nhtreport_SizeInMsg_messageDescriptor,
    &g_Nhtreport_EmptyMsg_messageDescriptor,
    (TMsgBuf_rpcFctEntry)&rpc_nhtreport_hc_nht_setReportLevel
  },
  /* 'tn_report_stdout' method descriptor (index=4) */
  {
    "tn_report_stdout",
    &g_Nhtreport_ReportTextInMsg_messageDescriptor,
    &g_Nhtreport_EmptyMsg_messageDescriptor,
    (TMsgBuf_rpcFctEntry)&rpc_nhtreport_tn_report_stdout
  },
  /* 'tn_report_stderr' method descriptor (index=5) */
  {
    "tn_report_stderr",
    &g_Nhtreport_ReportTextInMsg_messageDescriptor,
    &g_Nhtreport_EmptyMsg_messageDescriptor,
    (TMsgBuf_rpcFctEntry)&rpc_nhtreport_tn_report_stderr
  },
  /* 'tn_report_ftrace' method descriptor (index=6) */
  {
    "tn_report_ftrace",
    &g_Nhtreport_ReportFTraceInMsg_messageDescriptor,
    &g_Nhtreport_EmptyMsg_messageDescriptor,
    (TMsgBuf_rpcFctEntry)&rpc_nhtreport_tn_report_ftrace
  },
  /* 'hc_enable_ftrace' method descriptor (index=7) */
  {
    "hc_enable_ftrace",
    &g_Nhtreport_EmptyMsg_messageDescriptor,
    &g_Nhtreport_EmptyMsg_messageDescriptor,
    (TMsgBuf_rpcFctEntry)&rpc_nhtreport_hc_enable_ftrace
  },
  /* 'hc_disable_ftrace' method descriptor (index=8) */
  {
    "hc_disable_ftrace",
    &g_Nhtreport_EmptyMsg_messageDescriptor,
    &g_Nhtreport_EmptyMsg_messageDescriptor,
    (TMsgBuf_rpcFctEntry)&rpc_nhtreport_hc_disable_ftrace
  },
  /* 'hc_restore_ftrace' method descriptor (index=9) */
  {
    "hc_restore_ftrace",
    &g_Nhtreport_EmptyMsg_messageDescriptor,
    &g_Nhtreport_EmptyMsg_messageDescriptor,
    (TMsgBuf_rpcFctEntry)&rpc_nhtreport_hc_restore_ftrace
  },
  /* 'hc_getCmServerVersion' method descriptor (index=10) */
  {
    "hc_getCmServerVersion",
    &g_Nhtreport_EmptyMsg_messageDescriptor,
    &g_Nhtreport_ReportTextOutMsg_messageDescriptor,
    (TMsgBuf_rpcFctEntry)&rpc_nhtreport_hc_getCmServerVersion
  },
  /* 'hc_getNhtServerComponentVersion' method descriptor (index=11) */
  {
    "hc_getNhtServerComponentVersion",
    &g_Nhtreport_EmptyMsg_messageDescriptor,
    &g_Nhtreport_ReportTextOutMsg_messageDescriptor,
    (TMsgBuf_rpcFctEntry)&rpc_nhtreport_hc_getNhtServerComponentVersion
  }
};

const TMsgBuf_serviceDescriptor g_nhtreport_v1_2_0_serviceDescriptor =
{
  MSGBUF_SERVICE_DESCRIPTOR_MAGIC_ID,          /* field:   magic */
  "nhtreport_v1_2_0",                          /* field: * pServiceName */
  "nhtreport",                                 /* field: * pPackageName */
  0,                                           /* field:   methodId */
  12,                                          /* field:   n_methods */
  g_nhtreport_v1_2_0_serviceMethodsDescriptor, /* field: * pMethods */
};

