/* DO NOT EDIT THIS FILE!!!
 * This file was automatically generated by msgbuf compiler!
 *
 * This file contains the msgbuf structure definitions associated
 * to the package nhtreport.proto
 */

#ifndef _MSGBUF_NHTREPORT_H_
#define _MSGBUF_NHTREPORT_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*****************************************************************************
 * include files                                                             *
 ****************************************************************************/

#include "inc/xsd-c.h"

/*****************************************************************************
 * msgbuf message type definition                                            *
 ****************************************************************************/

typedef struct SNhtreport_ReportErrorInMsg  TNhtreport_ReportErrorInMsg;
typedef struct SNhtreport_ReportTraceInMsg  TNhtreport_ReportTraceInMsg;
typedef struct SNhtreport_ReportInfoInMsg   TNhtreport_ReportInfoInMsg;
typedef struct SNhtreport_EmptyMsg          TNhtreport_EmptyMsg;
typedef struct SNhtreport_SizeInMsg         TNhtreport_SizeInMsg;
typedef struct SNhtreport_GetSizeInMsg      TNhtreport_GetSizeInMsg;
typedef struct SNhtreport_ReportFTraceInMsg TNhtreport_ReportFTraceInMsg;
typedef struct SNhtreport_ReportTextInMsg   TNhtreport_ReportTextInMsg;
typedef struct SNhtreport_ReportTextOutMsg  TNhtreport_ReportTextOutMsg;


/*****************************************************************************
 * msgbuf enum type definition                                               *
 ****************************************************************************/


/*****************************************************************************
 * msgbuf message structure definition                                       *
 ****************************************************************************/

struct SNhtreport_ReportErrorInMsg
{
  TMsgBuf_desc    _pDesc;
  uint32_t        errorType;
  uint32_t        errorNumber;
  char         *  context;
  char         *  description;
};

struct SNhtreport_ReportTraceInMsg
{
  TMsgBuf_desc    _pDesc;
  uint32_t        errorType;
  char         *  filename;
  uint32_t        line;
  char         *  context;
  char         *  description;
};

struct SNhtreport_ReportInfoInMsg
{
  TMsgBuf_desc    _pDesc;
  uint32_t        errorType;
  char         *  context;
  char         *  description;
};

struct SNhtreport_EmptyMsg
{
  TMsgBuf_desc    _pDesc;
};

struct SNhtreport_SizeInMsg
{
  TMsgBuf_desc    _pDesc;
  uint32_t        value;
};

struct SNhtreport_GetSizeInMsg
{
  TMsgBuf_desc    _pDesc;
  uint32_t        value;
  TMsgBuf_bool    has_output;
};

struct SNhtreport_ReportFTraceInMsg
{
  TMsgBuf_desc    _pDesc;
  uint32_t        callId;
  uint32_t        type;
  char         *  text;
};

struct SNhtreport_ReportTextInMsg
{
  TMsgBuf_desc    _pDesc;
  char         *  text;
};

struct SNhtreport_ReportTextOutMsg
{
  TMsgBuf_desc    _pDesc;
  char         *  text;
};


/*****************************************************************************
 * msgbuf Message initialization  function                                   *
 ****************************************************************************/

void init_Nhtreport_ReportErrorInMsg  ( TNhtreport_ReportErrorInMsg  * pInstance );
void init_Nhtreport_ReportTraceInMsg  ( TNhtreport_ReportTraceInMsg  * pInstance );
void init_Nhtreport_ReportInfoInMsg   ( TNhtreport_ReportInfoInMsg   * pInstance );
void init_Nhtreport_EmptyMsg          ( TNhtreport_EmptyMsg          * pInstance );
void init_Nhtreport_SizeInMsg         ( TNhtreport_SizeInMsg         * pInstance );
void init_Nhtreport_GetSizeInMsg      ( TNhtreport_GetSizeInMsg      * pInstance );
void init_Nhtreport_ReportFTraceInMsg ( TNhtreport_ReportFTraceInMsg * pInstance );
void init_Nhtreport_ReportTextInMsg   ( TNhtreport_ReportTextInMsg   * pInstance );
void init_Nhtreport_ReportTextOutMsg  ( TNhtreport_ReportTextOutMsg  * pInstance );

/*****************************************************************************
 * msgbuf Message allocation function prototypes                             *
 ****************************************************************************/

TNhtreport_ReportErrorInMsg  * pAlloc_Nhtreport_ReportErrorInMsg  (void);
TNhtreport_ReportTraceInMsg  * pAlloc_Nhtreport_ReportTraceInMsg  (void);
TNhtreport_ReportInfoInMsg   * pAlloc_Nhtreport_ReportInfoInMsg   (void);
TNhtreport_EmptyMsg          * pAlloc_Nhtreport_EmptyMsg          (void);
TNhtreport_SizeInMsg         * pAlloc_Nhtreport_SizeInMsg         (void);
TNhtreport_GetSizeInMsg      * pAlloc_Nhtreport_GetSizeInMsg      (void);
TNhtreport_ReportFTraceInMsg * pAlloc_Nhtreport_ReportFTraceInMsg (void);
TNhtreport_ReportTextInMsg   * pAlloc_Nhtreport_ReportTextInMsg   (void);
TNhtreport_ReportTextOutMsg  * pAlloc_Nhtreport_ReportTextOutMsg  (void);

/*****************************************************************************
 * msgbuf Message deallocation function prototypes                           *
 ****************************************************************************/

void dealloc_Nhtreport_ReportErrorInMsg  (TNhtreport_ReportErrorInMsg  * pxInstance);
void dealloc_Nhtreport_ReportTraceInMsg  (TNhtreport_ReportTraceInMsg  * pxInstance);
void dealloc_Nhtreport_ReportInfoInMsg   (TNhtreport_ReportInfoInMsg   * pxInstance);
void dealloc_Nhtreport_EmptyMsg          (TNhtreport_EmptyMsg          * pxInstance);
void dealloc_Nhtreport_SizeInMsg         (TNhtreport_SizeInMsg         * pxInstance);
void dealloc_Nhtreport_GetSizeInMsg      (TNhtreport_GetSizeInMsg      * pxInstance);
void dealloc_Nhtreport_ReportFTraceInMsg (TNhtreport_ReportFTraceInMsg * pxInstance);
void dealloc_Nhtreport_ReportTextInMsg   (TNhtreport_ReportTextInMsg   * pxInstance);
void dealloc_Nhtreport_ReportTextOutMsg  (TNhtreport_ReportTextOutMsg  * pxInstance);

/*****************************************************************************
 * msgbuf enum test function prototype                                       *
 ****************************************************************************/


#ifdef __cplusplus
}
#endif /* __cplusplus */


#endif /* _MSGBUF_NHTREPORT_H_ */
