

// PAD_NAME: VDAC_IDACO_TV_APAD 0
#define RTD298X_QFP176_PIN_1_GPI_129(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 129, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_1_GPO_129(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 129, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_1_TRIO_129(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 129, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: BB_AI2L_APAD 1
#define RTD298X_QFP176_PIN_5_GPI_130(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 130, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_5_GPO_130(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 130, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_5_TRIO_130(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 130, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_5_PWM_6(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 6, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_5_UNIPWM_7(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 7, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: BB_AI2R_APAD 2
#define RTD298X_QFP176_PIN_6_GPI_131(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 131, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_6_GPO_131(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 131, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_6_TRIO_131(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 131, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_6_PWM_5(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 5, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_6_UNIPWM_1(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 1, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: BB_AI3L_APAD 3
#define RTD298X_QFP176_PIN_7_GPI_132(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 132, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_7_GPO_132(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 132, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_7_TRIO_132(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 132, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_7_PWM_7(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 7, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_7_UNIPWM_5(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 5, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: BB_AI3R_APAD 4
#define RTD298X_QFP176_PIN_8_GPI_133(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 133, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_8_GPO_133(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 133, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_8_TRIO_133(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 133, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_8_PWM_6(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 6, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_8_UNIPWM_7(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 7, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: BB_AIO1L_APAD 5
#define RTD298X_QFP176_PIN_10_GPI_136(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 136, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_10_GPO_136(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 136, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_10_TRIO_136(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 136, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_10_PWM_5(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 5, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_10_UNIPWM_1(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 1, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: BB_AIO1R_APAD 6
#define RTD298X_QFP176_PIN_11_GPI_137(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 137, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_11_GPO_137(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 137, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_11_TRIO_137(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 137, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: BB_HPOL_APAD:2 7
#define RTD298X_QFP176_PIN_13_GPI_138(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 138, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_13_GPO_138(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 138, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_13_TRIO_138(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 138, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_13_PWM_4(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 4, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_13_UNIPWM_4(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 4, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: BB_HPOR_APAD:2 8
#define RTD298X_QFP176_PIN_14_GPI_139(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 139, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_14_GPO_139(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 139, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_14_TRIO_139(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 139, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: BB_DIO1_APAD 9
#define RTD298X_QFP176_PIN_16_GPI_194(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 194, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_16_GPO_194(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 194, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_16_TRIO_194(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 194, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_16_PWM_6(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 6, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_16_UNIPWM_7(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 7, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: BB_DIO2_APAD 10
#define RTD298X_QFP176_PIN_17_GPI_195(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 195, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_17_GPO_195(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 195, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_17_TRIO_195(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 195, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_17_PWM_4(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 4, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: BB_DIO3_APAD 11
#define RTD298X_QFP176_PIN_15_GPI_196(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 196, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_15_GPO_196(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 196, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_15_TRIO_196(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 196, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_15_PWM_7(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 7, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_15_UNIPWM_5(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 5, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: HSDP_2_APAD 98
#define RTD298X_QFP176_PIN_36_PWM_4(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 4, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_36_UNIPWM_7(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 7, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: HSDM_2_APAD 97
#define RTD298X_QFP176_PIN_37_PWM_3(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 3, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_37_UNIPWM_5(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 5, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: pad_gpio_0_io 12
#define RTD298X_QFP176_PIN_38_GPI_0(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 0, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_38_GPO_0(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 0, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_38_TRIO_0(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 0, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: pad_gpio_1_io 13
#define RTD298X_QFP176_PIN_39_GPI_1(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 1, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_39_GPO_1(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 1, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_39_TRIO_1(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 1, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: pad_gpio_2_io 14
#define RTD298X_QFP176_PIN_40_GPI_2(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 2, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_40_GPO_2(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 2, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_40_TRIO_2(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 2, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: pad_gpio_16_io 15
#define RTD298X_QFP176_PIN_42_GPI_16(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 16, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_42_GPO_16(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 16, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_42_TRIO_16(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 16, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_42_PWM_4(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 4, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_42_UNIPWM_7(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 7, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: pad_gpio_17_io 16
#define RTD298X_QFP176_PIN_43_GPI_17(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 17, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_43_GPO_17(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 17, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_43_TRIO_17(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 17, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_43_PWM_1(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 1, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_43_UNIPWM_1(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 1, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: pad_gpio_18_io 17
#define RTD298X_QFP176_PIN_44_GPI_18(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 18, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_44_GPO_18(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 18, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_44_TRIO_18(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 18, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_44_PWM_5(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 5, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: pad_gpio_19_io 18
#define RTD298X_QFP176_PIN_45_PWM_4(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 4, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_45_UNIPWM_7(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 7, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: pad_gpio_39_io 19
#define RTD298X_QFP176_PIN_46_PWM_5(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 5, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: pad_gpio_40_io 20
#define RTD298X_QFP176_PIN_47_GPI_40(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 40, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_47_GPO_40(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 40, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_47_TRIO_40(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 40, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_47_PWM_6(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 6, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_47_UNIPWM_2(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 2, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: pad_gpio_41_io 21
#define RTD298X_QFP176_PIN_48_GPI_41(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 41, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_48_GPO_41(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 41, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_48_TRIO_41(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 41, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_48_PWM_7(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 7, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: pad_gpio_42_io 22
#define RTD298X_QFP176_PIN_49_GPI_42(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 42, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_49_GPO_42(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 42, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_49_TRIO_42(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 42, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: pad_gpio_35_io 23
#define RTD298X_QFP176_PIN_53_PWM_3(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 3, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_53_UNIPWM_6(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 6, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: pad_gpio_44_io 24
#define RTD298X_QFP176_PIN_54_GPI_44(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 44, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_54_GPO_44(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 44, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_54_TRIO_44(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 44, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_54_PWM_0(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 0, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: pad_gpio_45_io 25
#define RTD298X_QFP176_PIN_55_GPI_45(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 45, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_55_GPO_45(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 45, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_55_TRIO_45(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 45, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_55_PWM_1(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 1, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: pad_gpio_46_io 26
#define RTD298X_QFP176_PIN_56_GPI_46(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 46, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_56_GPO_46(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 46, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_56_TRIO_46(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 46, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_56_PWM_2(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 2, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: pad_gpio_47_io 27
#define RTD298X_QFP176_PIN_57_GPI_47(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 47, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_57_GPO_47(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 47, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_57_TRIO_47(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 47, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_57_PWM_3(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 3, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: pad_gpio_48_io 28
#define RTD298X_QFP176_PIN_58_GPI_48(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 48, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_58_GPO_48(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 48, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_58_TRIO_48(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 48, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_58_PWM_4(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 4, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: pad_gpio_49_io 29
#define RTD298X_QFP176_PIN_59_GPI_49(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 49, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_59_GPO_49(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 49, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_59_TRIO_49(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 49, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_59_PWM_5(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 5, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: pad_gpio_50_io 30
#define RTD298X_QFP176_PIN_60_PWM_6(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 6, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: pad_gpio_51_io 31
#define RTD298X_QFP176_PIN_61_PWM_7(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 7, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: pad_gpio_52_io 32
#define RTD298X_QFP176_PIN_62_GPI_52(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 52, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_62_GPO_52(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 52, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_62_TRIO_52(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 52, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_62_PWM_0(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 0, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: pad_gpio_56_io 33
#define RTD298X_QFP176_PIN_63_GPI_56(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 56, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_63_GPO_56(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 56, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_63_TRIO_56(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 56, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_63_PWM_1(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 1, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: pad_gpio_53_io 34
#define RTD298X_QFP176_PIN_64_GPI_53(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 53, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_64_GPO_53(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 53, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_64_TRIO_53(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 53, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_64_PWM_5(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 5, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_64_UNIPWM_3(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 3, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: pad_gpio_54_io 35
#define RTD298X_QFP176_PIN_65_GPI_54(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 54, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_65_GPO_54(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 54, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_65_TRIO_54(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 54, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_65_PWM_2(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 2, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_65_UNIPWM_2(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 2, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: PLT_P0_TXHP 36
#define RTD298X_QFP176_PIN_74_GPI_141(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 141, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_74_GPO_141(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 141, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_74_TRIO_141(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 141, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_74_PWM_3(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 3, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_74_UNIPWM_6(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 6, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: PLT_P0_TXGP 37
#define RTD298X_QFP176_PIN_75_GPI_81(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 81, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_75_GPO_81(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 81, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_75_TRIO_81(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 81, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_75_PWM_3(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 3, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_75_UNIPWM_6(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 6, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: PLT_P0_TXGN 38
#define RTD298X_QFP176_PIN_76_GPI_82(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 82, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_76_GPO_82(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 82, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_76_TRIO_82(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 82, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_76_PWM_1(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 1, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_76_UNIPWM_1(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 1, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: PLT_P0_TXFP 39
#define RTD298X_QFP176_PIN_77_GPI_57(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 57, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_77_GPO_57(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 57, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_77_TRIO_57(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 57, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_77_PWM_2(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 2, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_77_UNIPWM_2(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 2, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: PLT_P0_TXFN 40
#define RTD298X_QFP176_PIN_78_GPI_58(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 58, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_78_GPO_58(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 58, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_78_TRIO_58(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 58, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_78_PWM_3(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 3, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_78_UNIPWM_3(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 3, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: PLT_P0_TXEP 41
#define RTD298X_QFP176_PIN_79_GPI_59(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 59, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_79_GPO_59(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 59, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_79_TRIO_59(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 59, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: PLT_P0_TXEN 42
#define RTD298X_QFP176_PIN_80_GPI_60(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 60, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_80_GPO_60(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 60, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_80_TRIO_60(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 60, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: PLT_P0_TXDP 43
#define RTD298X_QFP176_PIN_81_GPI_61(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 61, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_81_GPO_61(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 61, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_81_TRIO_61(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 61, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: PLT_P0_TXDN 44
#define RTD298X_QFP176_PIN_82_GPI_62(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 62, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_82_GPO_62(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 62, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_82_TRIO_62(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 62, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: PLT_P0_TXCP 45
#define RTD298X_QFP176_PIN_83_GPI_63(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 63, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_83_GPO_63(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 63, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_83_TRIO_63(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 63, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: PLT_P0_TXCN 46
#define RTD298X_QFP176_PIN_84_GPI_64(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 64, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_84_GPO_64(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 64, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_84_TRIO_64(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 64, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: PLT_P0_TXBP 47
#define RTD298X_QFP176_PIN_85_GPI_65(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 65, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_85_GPO_65(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 65, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_85_TRIO_65(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 65, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: PLT_P0_TXBN 48
#define RTD298X_QFP176_PIN_86_GPI_66(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 66, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_86_GPO_66(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 66, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_86_TRIO_66(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 66, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: PLT_P0_TXAP 49
#define RTD298X_QFP176_PIN_87_GPI_67(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 67, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_87_GPO_67(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 67, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_87_TRIO_67(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 67, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_87_PWM_4(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 4, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_87_UNIPWM_4(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 4, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: PLT_P0_TXAN 50
#define RTD298X_QFP176_PIN_88_GPI_68(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 68, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_88_GPO_68(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 68, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_88_TRIO_68(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 68, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_88_PWM_5(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 5, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_88_UNIPWM_5(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 5, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: PLT_P1_TXGP 51
#define RTD298X_QFP176_PIN_90_GPI_83(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 83, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_90_GPO_83(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 83, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_90_TRIO_83(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 83, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_90_PWM_6(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 6, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_90_UNIPWM_6(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 6, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: PLT_P1_TXGN 52
#define RTD298X_QFP176_PIN_91_GPI_84(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 84, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_91_GPO_84(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 84, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_91_TRIO_84(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 84, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_91_PWM_7(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 7, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_91_UNIPWM_7(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 7, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: PLT_P1_TXFP 53
#define RTD298X_QFP176_PIN_92_PWM_6(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 6, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: PLT_P1_TXFN 54
#define RTD298X_QFP176_PIN_93_PWM_7(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 7, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: PLT_P1_TXEP 55
#define RTD298X_QFP176_PIN_94_GPI_71(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 71, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_94_GPO_71(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 71, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_94_TRIO_71(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 71, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: PLT_P1_TXEN 56
#define RTD298X_QFP176_PIN_95_GPI_72(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 72, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_95_GPO_72(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 72, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_95_TRIO_72(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 72, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: PLT_P1_TXDP 57
#define RTD298X_QFP176_PIN_96_GPI_73(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 73, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_96_GPO_73(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 73, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_96_TRIO_73(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 73, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_96_PWM_0(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 0, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_96_UNIPWM_0(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 0, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: PLT_P1_TXDN 58
#define RTD298X_QFP176_PIN_97_GPI_74(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 74, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_97_GPO_74(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 74, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_97_TRIO_74(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 74, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_97_PWM_1(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 1, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_97_UNIPWM_1(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 1, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: PLT_P1_TXCP 59
#define RTD298X_QFP176_PIN_98_GPI_75(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 75, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_98_GPO_75(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 75, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_98_TRIO_75(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 75, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: PLT_P1_TXCN 60
#define RTD298X_QFP176_PIN_99_GPI_76(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 76, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_99_GPO_76(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 76, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_99_TRIO_76(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 76, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: PLT_P1_TXBP 61
#define RTD298X_QFP176_PIN_100_GPI_77(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 77, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_100_GPO_77(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 77, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_100_TRIO_77(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 77, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_100_PWM_2(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 2, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: PLT_P1_TXBN 62
#define RTD298X_QFP176_PIN_101_PWM_3(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 3, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: PLT_P1_TXAP 63
#define RTD298X_QFP176_PIN_102_GPI_79(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 79, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_102_GPO_79(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 79, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_102_TRIO_79(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 79, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_102_PWM_4(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 4, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: PLT_P1_TXAN 64
#define RTD298X_QFP176_PIN_103_GPI_80(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 80, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_103_GPO_80(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 80, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_103_TRIO_80(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 80, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_103_PWM_5(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 5, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: pad_st_gpio_7_io 65
#define RTD298X_QFP176_PIN_105_ISO_GPI_7(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 7, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_105_ISO_GPO_7(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 7, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_105_ISO_TRIO_7(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 7, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: pad_st_gpio_8_io 66
#define RTD298X_QFP176_PIN_106_ISO_GPI_8(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 8, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_106_ISO_GPO_8(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 8, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_106_ISO_TRIO_8(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 8, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: pad_st_gpio_9_io 67
#define RTD298X_QFP176_PIN_107_ISO_GPI_9(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 9, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_107_ISO_GPO_9(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 9, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_107_ISO_TRIO_9(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 9, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: pad_st_gpio_10_io 68
#define RTD298X_QFP176_PIN_108_ISO_GPI_10(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 10, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_108_ISO_GPO_10(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 10, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_108_ISO_TRIO_10(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 10, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: pad_st_gpio_11_io 69
#define RTD298X_QFP176_PIN_109_ISO_GPI_11(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 11, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_109_ISO_GPO_11(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 11, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_109_ISO_TRIO_11(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 11, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_109_ISO_PWM_0(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY) \
        __PIN(PCB_PIN_TYPE_ISO_PWM, 0, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_109_ISO_UNIPWM_0(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX,INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_ISO_UNIPWM, 0, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: pad_st_gpio_12_io 70
#define RTD298X_QFP176_PIN_110_ISO_GPI_12(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 12, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_110_ISO_GPO_12(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 12, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_110_ISO_TRIO_12(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 12, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_110_ISO_PWM_0(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY) \
        __PIN(PCB_PIN_TYPE_ISO_PWM, 0, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: pad_st_gpio_13_io 71
#define RTD298X_QFP176_PIN_111_ISO_GPI_13(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 13, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_111_ISO_GPO_13(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 13, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_111_ISO_TRIO_13(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 13, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_111_ISO_PWM_1(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY) \
        __PIN(PCB_PIN_TYPE_ISO_PWM, 1, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
// PAD_NAME: pad_st_gpio_14_io 72
#define RTD298X_QFP176_PIN_112_ISO_GPI_14(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 14, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_112_ISO_GPO_14(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 14, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_112_ISO_TRIO_14(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 14, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: pad_st_gpio_15_io 73
#define RTD298X_QFP176_PIN_113_ISO_GPI_15(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 15, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_113_ISO_GPO_15(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 15, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_113_ISO_TRIO_15(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 15, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: pad_st_gpio_16_io 74
#define RTD298X_QFP176_PIN_114_ISO_GPI_16(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 16, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_114_ISO_GPO_16(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 16, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_114_ISO_TRIO_16(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 16, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: pad_st_gpio_17_io 75
#define RTD298X_QFP176_PIN_115_ISO_GPI_17(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 17, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_115_ISO_GPO_17(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 17, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_115_ISO_TRIO_17(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 17, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: pad_st_gpio_18_io 76
#define RTD298X_QFP176_PIN_116_ISO_GPI_18(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 18, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_116_ISO_GPO_18(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 18, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_116_ISO_TRIO_18(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 18, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: pad_st_gpio_19_io 77
#define RTD298X_QFP176_PIN_117_ISO_GPI_19(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 19, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_117_ISO_GPO_19(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 19, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_117_ISO_TRIO_19(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 19, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: pad_st_gpio_20_io 78
#define RTD298X_QFP176_PIN_118_ISO_GPI_20(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 20, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_118_ISO_GPO_20(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 20, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_118_ISO_TRIO_20(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 20, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: pad_st_gpio_21_io 79
#define RTD298X_QFP176_PIN_119_ISO_GPI_21(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 21, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_119_ISO_GPO_21(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 21, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_119_ISO_TRIO_21(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 21, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: pad_st_gpio_22_io 80
#define RTD298X_QFP176_PIN_120_ISO_GPI_22(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 22, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_120_ISO_GPO_22(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 22, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_120_ISO_TRIO_22(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 22, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: pad_st_gpio_23_io 81
// PAD_NAME: pad_st_gpio_24_io 82
#define RTD298X_QFP176_PIN_122_ISO_GPI_24(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 24, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_122_ISO_GPO_24(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 24, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_122_ISO_TRIO_24(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 24, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: LSADC_REF_APAD 83
#define RTD298X_QFP176_PIN_123_ISO_GPI_0(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 0, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_123_ISO_GPO_0(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 0, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_123_ISO_TRIO_0(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 0, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: LSADC0_APAD 84
#define RTD298X_QFP176_PIN_124_ISO_GPI_1(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 1, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_124_ISO_GPO_1(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 1, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_124_ISO_TRIO_1(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 1, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_124_LSADC_VOLTAGE_0(HITVALUE, TORRENCE) \
        __PIN(PCB_PIN_TYPE_LSADC, 0, PCB_LSADC_TYPE_VOLTAGE, HITVALUE, TORRENCE, 0, 0, 0)
#define RTD298X_QFP176_PIN_124_LSADC_CURRENT_0(HITVALUE, TORRENCE) \
        __PIN(PCB_PIN_TYPE_LSADC, 0, PCB_LSADC_TYPE_CURRENT, HITVALUE, TORRENCE, 0, 0, 0)
// PAD_NAME: LSADC1_APAD 85
#define RTD298X_QFP176_PIN_125_ISO_GPI_2(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 2, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_125_ISO_GPO_2(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 2, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_125_ISO_TRIO_2(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 2, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_125_LSADC_VOLTAGE_1(HITVALUE, TORRENCE) \
        __PIN(PCB_PIN_TYPE_LSADC, 1, PCB_LSADC_TYPE_VOLTAGE, HITVALUE, TORRENCE, 0, 0, 0)
#define RTD298X_QFP176_PIN_125_LSADC_CURRENT_1(HITVALUE, TORRENCE) \
        __PIN(PCB_PIN_TYPE_LSADC, 1, PCB_LSADC_TYPE_CURRENT, HITVALUE, TORRENCE, 0, 0, 0)
// PAD_NAME: LSADC2_APAD 86
#define RTD298X_QFP176_PIN_126_ISO_GPI_3(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 3, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_126_ISO_GPO_3(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 3, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_126_ISO_TRIO_3(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 3, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_126_LSADC_VOLTAGE_2(HITVALUE, TORRENCE) \
        __PIN(PCB_PIN_TYPE_LSADC, 2, PCB_LSADC_TYPE_VOLTAGE, HITVALUE, TORRENCE, 0, 0, 0)
#define RTD298X_QFP176_PIN_126_LSADC_CURRENT_2(HITVALUE, TORRENCE) \
        __PIN(PCB_PIN_TYPE_LSADC, 2, PCB_LSADC_TYPE_CURRENT, HITVALUE, TORRENCE, 0, 0, 0)
// PAD_NAME: LSADC7_APAD 87
#define RTD298X_QFP176_PIN_127_ISO_GPI_6(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 6, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_127_ISO_GPO_6(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 6, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_127_ISO_TRIO_6(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 6, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_127_LSADC_VOLTAGE_7(HITVALUE, TORRENCE) \
        __PIN(PCB_PIN_TYPE_LSADC, 7, PCB_LSADC_TYPE_VOLTAGE, HITVALUE, TORRENCE, 0, 0, 0)
#define RTD298X_QFP176_PIN_127_LSADC_CURRENT_7(HITVALUE, TORRENCE) \
        __PIN(PCB_PIN_TYPE_LSADC, 7, PCB_LSADC_TYPE_CURRENT, HITVALUE, TORRENCE, 0, 0, 0)
// PAD_NAME: STB_GPIO_APAD 88
#define RTD298X_QFP176_PIN_129_ISO_GPI_47(INVERT)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 47, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0) 
#define RTD298X_QFP176_PIN_129_ISO_GPO_47(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 47, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_129_ISO_TRIO_47(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_ISO_GPIO, 47, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_129_ISO_UNIPWM_0(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX,INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_ISO_UNIPWM, 0, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: VSYNC_APAD 89
#define RTD298X_QFP176_PIN_161_GPI_111(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 111, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_161_GPO_111(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 111, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_161_TRIO_111(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 111, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: HSYNC_APAD 90
#define RTD298X_QFP176_PIN_162_GPI_112(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 112, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_162_GPO_112(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 112, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_162_TRIO_112(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 112, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: VIN_0P_APAD 91
#define RTD298X_QFP176_PIN_163_GPI_113(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 113, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_163_GPO_113(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 113, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_163_TRIO_113(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 113, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: VIN_BN_APAD 92
#define RTD298X_QFP176_PIN_164_GPI_114(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 114, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_164_GPO_114(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 114, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_164_TRIO_114(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 114, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: VIN_1P_APAD 93
#define RTD298X_QFP176_PIN_165_GPI_115(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 115, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_165_GPO_115(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 115, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_165_TRIO_115(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 115, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_165_PWM_3(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 3, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_165_UNIPWM_7(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 7, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: VIN_2P_APAD 94
#define RTD298X_QFP176_PIN_166_GPI_116(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 116, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_166_GPO_116(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 116, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_166_TRIO_116(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 116, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_166_PWM_3(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 3, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_166_UNIPWM_5(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 5, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)
// PAD_NAME: VIN_13P_APAD 95
#define RTD298X_QFP176_PIN_172_GPI_126(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 126, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_172_GPO_126(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 126, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_172_TRIO_126(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 126, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: VIN_A0N_APAD 96
#define RTD298X_QFP176_PIN_173_GPI_123(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 123, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_173_GPO_123(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 123, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_173_TRIO_123(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 123, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
// PAD_NAME: VIN_12P_APAD 97
#define RTD298X_QFP176_PIN_174_GPI_122(INVERT) \
        __PIN(PCB_PIN_TYPE_GPIO, 122, PCB_GPIO_TYPE_INPUT, INVERT, 0, 0, 0, 0)
#define RTD298X_QFP176_PIN_174_GPO_122(INVERT, INIT_VALUE) \
        __PIN(PCB_PIN_TYPE_GPIO, 122, PCB_GPIO_TYPE_OUPUT, INVERT, INIT_VALUE, 0, 0, 0) 
#define RTD298X_QFP176_PIN_174_TRIO_122(INVERT, INIT_VALUE)	\
        __PIN(PCB_PIN_TYPE_GPIO, 122, PCB_GPIO_TYPE_TRI_IO, INVERT, INIT_VALUE, 0, 0, 0)
#define RTD298X_QFP176_PIN_174_PWM_3(INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)	\
        __PIN(PCB_PIN_TYPE_PWM, 3, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, 0)
#define RTD298X_QFP176_PIN_174_UNIPWM_5(PWM_NUM, INVERT, FREQ_HZ, DUTY_MAX, INIT_DUTY)		\
        __PIN(PCB_PIN_TYPE_UNIPWM, 5, ((((INVERT) != 0) << 7) | (((FREQ_HZ) >> 16) & 0x7F)), (((FREQ_HZ) >> 8) & 0xFF) , ((FREQ_HZ) &0xFF) , DUTY_MAX, INIT_DUTY, PWM_NUM)

