#ifndef __EMI_H__
#define __EMI_H__

typedef enum {

    // MPEG - CSA
    EMI_STREAM_DVB_CSAV2    = 0x0000,
    EMI_STREAM_DVB_CSAV3    = 0x0001,

    // MPEG - ASA
    EMI_STREAM_ASA_64       = 0x0010,
    EMI_STREAM_ASA_128      = 0x0011,

    // MPEG - AES
    EMI_STREAM_AES_128_IDSA                      = 0x0020,
    EMI_STREAM_AES_128_ECB_TERMINATION_IN_CLEAR  = 0x0021,
    EMI_STREAM_AES_128_CBC_IV_MODIFIABLE_TERMINATION_IN_CLEAR  = 0x0022,

    // MPEG - TDES
    EMI_STREAM_TDES_K1K2_CBC_ZEROIV_TERMINATION_DVS_042 = 0x0040,
    EMI_STREAM_TDES_K1K2_ECB_TERMINATION_IN_CLEAR = 0x0042,

    // NORMAL - AES
    EMI_NORMAL_AES_128_CBC_ZEROIV_TERMINATION_IN_CLEAR  = 0x4020,
    EMI_NORMAL_AES_128_ECB_TERMINATION_IN_CLEAR         = 0x4021,
    EMI_NORMAL_AES_128_CBC_MPEG_STANDARD                = 0x4022,
    EMI_NORMAL_AES_128_CBC_APPLE_LIVE_STREAMING         = 0x4023,
    EMI_NORMAL_AES_128_CTR_MPEG_STANDARD                = 0x4024,
    EMI_NORMAL_AES_128_CBC_IV_MODIFIABLE_TERMINATION_IN_CLEAR = 0x4026,
    EMI_NORMAL_AES_128_CTR                              = 0x4027,

    // NORMAL - TDES
    EMI_NORMAL_TES_K1K2_CBC_ZERO_IV_TERMINATION_IN_CLEAR = 0x4040,
    EMI_NORMAL_TES_K1K2_ECB_TERMINATION_IN_CLEAR = 0x4041,
    EMI_NORMAL_TES_K1K2_CBC_IV_MODIFIABLE_TERMINATION_IN_CLEAR = 0x4043,

}EMI_TYPE;

#ifdef __cplusplus
extern "C" {
#endif

extern const char* EmiStr(EMI_TYPE Emi);

#ifdef __cplusplus
}
#endif


#endif //__EMI_H__