##############################################################################
#
# Data Parameters for SCS Param Area
#
##############################################################################
Address_Of_DTE_Boot_Code_Area=0x00020000
SCS_Total_Area_Size_1=0x00040000
SCS_Total_Area_Size_2=0x00060000
SCS_Total_Area_Size_3=0x00080000
SCS_Total_Area_Size_4=0x00100000
SCS_Total_Area_Size_Selection=0x00000000

