/* DO NOT EDIT THIS FILE!!!
 * This file was automatically generated by msgbuf compiler!
 *
 * This file contains the msgbuf structure definitions associated
 * to the package nhtbsd.proto
 */

#ifndef _RPC_NHTBSD_H_
#define _RPC_NHTBSD_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*****************************************************************************
 * include files                                                             *
 ****************************************************************************/

#include "inc/msgbuf_types.h"



/*****************************************************************************
 * RPC service handle reference                                              *
 ****************************************************************************/

extern const TMsgBuf_serviceHandle gRpcServiceHandle_nhtbsd;


#ifdef __cplusplus
}
#endif /* __cplusplus */


#endif /* _RPC_NHTBSD_H_ */
