/* DO NOT EDIT THIS FILE!!!
 * This file was automatically generated by msgbuf compiler!
 *
 * This file contains the msgbuf structure definitions associated
 * to the package nhtsec.proto
 */

#ifndef __MSGBUF_EXPORT_NHTSEC_H_
#define __MSGBUF_EXPORT_NHTSEC_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*****************************************************************************
 * include files                                                             *
 ****************************************************************************/


#include "inc/xsd-c.h"
#include "src/msgbuf_nhtsec.h"



/*****************************************************************************
 * message descriptor prototype                                              *
 ****************************************************************************/

extern const TMsgBuf_messageDescriptor g_Nhtsec_EmptyMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_SysInBytesMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_SysOutBytesMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_SecTableOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_OptOutput1InMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_ValueOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_BytesOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_StringOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_CryptoProcessInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_RsaGenKeyInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_RsaGenKeyOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_RsaPublicEncryptInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_RsaPrivateEncryptInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_RsaPublicDecryptInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_RsaPrivateDecryptInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_RsaDecryptOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_RsaComputeCrtParamsInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_RsaComputeCrtParamsOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_DhGenerateKeyInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_DhGenerateKeyOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_DhComputeKeyInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_HandleOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_ShaUpdateInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_StatusOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_ShaFinalInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_HmacShaInitInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_GenerateRandomBytesInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_EcParamsMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_EcdsaGenerateKeyInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_EcdsaGenerateKeyOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_EcdsaSignInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_EcdsaSignOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_EcdsaVerifyInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_EcdhGenerateInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_EcdhGenerateOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_EcdhComputeKeyInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_HandleInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_SetClearTextKeyInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_Set2LevelProtectedKeyInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_UseCertKeyInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_SessionCryptoProcessInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_UseFlashProtKeyInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_R2rMonteCarloParamsInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_R2rMonteCarloRunInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_TransportIdOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_TransportIdInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_StreamSessionOpenInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_Set0LevelProtectedKeyInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_Set1LevelProtectedKeyInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_SetMetadataInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_SizeInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_EcmCallBackMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_DemuxServiceInfoMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_DemuxEcmInfoMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_OpenDscTransportSessionInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_OpenScrTransportSessionInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_WaitOnCompletionInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtsec_SetIvInMsg_messageDescriptor;

/*****************************************************************************
 * enum descriptor prototype                                                 *
 ****************************************************************************/


/*****************************************************************************
 * service descriptor prototype                                              *
 ****************************************************************************/

extern const TMsgBuf_serviceDescriptor g_nhtsec_v5_1_0_serviceDescriptor;

#ifdef __cplusplus
}
#endif /* __cplusplus */


#endif /* __MSGBUF_EXPORT_NHTSEC_H_ */
