/* DO NOT EDIT THIS FILE!!!
 * This file was automatically generated by msgbuf compiler!
 *
 * This file contains the msgbuf structure definitions associated
 * to the package nhtcert.proto
 */


/*****************************************************************************
 * include files                                                             *
 ****************************************************************************/

#include "inc/msgbuf_sys_malloc.h"
#include <stddef.h>
#include "src/msgbuf_nhtcert.h"
#include "inc/rpc_nhtcert.h"
#include "src/_msgbuf_nhtcert.h"
#include "src/rpc_nhtcert_api.h"


/*****************************************************************************
 * public rpc service handle                                                 *
 ****************************************************************************/

const TMsgBuf_serviceHandle gRpcServiceHandle_nhtcert = (TMsgBuf_serviceHandle)&g_nhtcert_v1_0_1_serviceDescriptor;


/*****************************************************************************
 * nested message descriptor prototype                                       *
 ****************************************************************************/


/*****************************************************************************
 * Generate default value implementation                                     *
 ****************************************************************************/


/*****************************************************************************
 * enum descriptor implementation                                            *
 ****************************************************************************/

const TMsgBuf_enumValue g_nhtcert_cert_status_enum_values_by_number[6] =
{
  { 0, "NO_ERROR",   "NHTCERT_CERT_STATUS_NO_ERROR   " },
  { 1, "BAD_HANDLE", "NHTCERT_CERT_STATUS_BAD_HANDLE " },
  { 2, "BAD_EMI",    "NHTCERT_CERT_STATUS_BAD_EMI    " },
  { 3, "BAD_USAGE",  "NHTCERT_CERT_STATUS_BAD_USAGE  " },
  { 4, "TIMEOUT",    "NHTCERT_CERT_STATUS_TIMEOUT    " },
  { 5, "ERROR",      "NHTCERT_CERT_STATUS_ERROR      " }
};

const TMsgBuf_enumDescriptor g_nhtcert_cert_status_enumDescriptor =
{
  MSGBUF_ENUM_DESCRIPTOR_MAGIC_ID,             /* field:   magic */
  "Nhtcert_CertStatus",                        /* filed: * pName*/
  "certStatus",                                /* field: * pShortName */
  "Nhtcert_CertStatus",                        /* field: * c_name */
  "nhtcert",                                   /* field: * pPackageName*/
  6,                                           /* field:   n_values */
  g_nhtcert_cert_status_enum_values_by_number/* field: * pValues */
};

const TMsgBuf_enumValue g_nhtcert_timeout_type_enum_values_by_number[2] =
{
  { 0, "TIMEOUT_DEFAULT", "NHTCERT_TIMEOUT_TYPE_TIMEOUT_DEFAULT " },
  { 1, "TIMEOUT_OTP",     "NHTCERT_TIMEOUT_TYPE_TIMEOUT_OTP     " }
};

const TMsgBuf_enumDescriptor g_nhtcert_timeout_type_enumDescriptor =
{
  MSGBUF_ENUM_DESCRIPTOR_MAGIC_ID,              /* field:   magic */
  "Nhtcert_TimeoutType",                        /* filed: * pName*/
  "timeoutType",                                /* field: * pShortName */
  "Nhtcert_TimeoutType",                        /* field: * c_name */
  "nhtcert",                                    /* field: * pPackageName*/
  2,                                            /* field:   n_values */
  g_nhtcert_timeout_type_enum_values_by_number/* field: * pValues */
};


/*****************************************************************************
 * message descriptor static init implementation                             *
 ****************************************************************************/

/* Default "TNhtcert_EmptyMsg" structure init value */
static const TNhtcert_EmptyMsg g_empty_msg_default_value =
{
  (TMsgBuf_desc)&g_Nhtcert_EmptyMsg_messageDescriptor,/* Base msg descriptor ref */
};

/* Default "TNhtcert_CertStatusOutMsg" structure init value */
static const TNhtcert_CertStatusOutMsg g_certStatus_outMsg_default_value =
{
  (TMsgBuf_desc)&g_Nhtcert_CertStatusOutMsg_messageDescriptor,/* Base msg descriptor ref */
  NHTCERT_CERT_STATUS_NOERROR                        /* field: required TNhtcert_CertStatus retStatus */
};

/* Default "TNhtcert_HandleOutMsg" structure init value */
static const TNhtcert_HandleOutMsg g_handle_outMsg_default_value =
{
  (TMsgBuf_desc)&g_Nhtcert_HandleOutMsg_messageDescriptor,/* Base msg descriptor ref */
  NHTCERT_CERT_STATUS_NOERROR,                   /* field: required TNhtcert_CertStatus retStatus */
  0, 0                                           /* field: optional int64_t             handle    */
};

/* Default "TNhtcert_CertCommandInMsg" structure init value */
static const TNhtcert_CertCommandInMsg g_certCommand_inMsg_default_value =
{
  (TMsgBuf_desc)&g_Nhtcert_CertCommandInMsg_messageDescriptor,/* Base msg descriptor ref */
  {0, NULL},                                         /* field: optional TMsgBuf_bytes inputData   */
  {0, NULL},                                         /* field: optional TMsgBuf_bytes opcodes     */
  0                                                  /* field: required int32_t       timeoutType */
};

/* Default "TNhtcert_CertCommandOutMsg" structure init value */
static const TNhtcert_CertCommandOutMsg g_certCommand_outMsg_default_value =
{
  (TMsgBuf_desc)&g_Nhtcert_CertCommandOutMsg_messageDescriptor,/* Base msg descriptor ref */
  {0, NULL},                                          /* field: optional TMsgBuf_bytes outputData */
  {0, NULL}                                           /* field: optional TMsgBuf_bytes status     */
};

/* Default "TNhtcert_CertTableHandleOutMsg" structure init value */
static const TNhtcert_CertTableHandleOutMsg g_certTableHandle_outMsg_default_value =
{
  (TMsgBuf_desc)&g_Nhtcert_CertTableHandleOutMsg_messageDescriptor,/* Base msg descriptor ref */
  0, 0,                                                   /* field: optional int64_t  handle     */
  0                                                       /* field: required uint32_t apiVersion */
};

/* Default "TNhtcert_CertLockInMsg" structure init value */
static const TNhtcert_CertLockInMsg g_certLock_inMsg_default_value =
{
  (TMsgBuf_desc)&g_Nhtcert_CertLockInMsg_messageDescriptor,/* Base msg descriptor ref */
  0                                               /* field: required TMsgBuf_bool has_output */
};

/* Default "TNhtcert_CertUnlockInMsg" structure init value */
static const TNhtcert_CertUnlockInMsg g_certUnlock_inMsg_default_value =
{
  (TMsgBuf_desc)&g_Nhtcert_CertUnlockInMsg_messageDescriptor,/* Base msg descriptor ref */
  0, 0                                              /* field: optional int64_t resHandle */
};

/* Default "TNhtcert_CertExchangeInMsg" structure init value */
static const TNhtcert_CertExchangeInMsg g_certExchange_inMsg_default_value =
{
  (TMsgBuf_desc)&g_Nhtcert_CertExchangeInMsg_messageDescriptor,/* Base msg descriptor ref */
  0, 0,                                               /* field: optional int64_t                   resHandle           */
  0, NULL,                                            /* field: repeated TNhtcert_CertCommandInMsg certCommands        */
  0                                                   /* field: required TMsgBuf_bool              hasProcessedCmdSize */
};

/* Default "TNhtcert_CertExchangeOutMsg" structure init value */
static const TNhtcert_CertExchangeOutMsg g_certExchange_outMsg_default_value =
{
  (TMsgBuf_desc)&g_Nhtcert_CertExchangeOutMsg_messageDescriptor,/* Base msg descriptor ref */
  NHTCERT_CERT_STATUS_NOERROR,                         /* field: required TNhtcert_CertStatus        retStatus     */
  0,                                                   /* field: required uint32_t                   processedCmds */
  0, NULL                                              /* field: repeated TNhtcert_CertCommandOutMsg certCommands  */
};

/* Default "TNhtcert_CertGetSingleInfoInMsg" structure init value */
static const TNhtcert_CertGetSingleInfoInMsg g_certGetSingleInfo_inMsg_default_value =
{
  (TMsgBuf_desc)&g_Nhtcert_CertGetSingleInfoInMsg_messageDescriptor,/* Base msg descriptor ref */
  0                                                        /* field: required TMsgBuf_bool has_output */
};

/* Default "TNhtcert_CertGetVersionOutMsg" structure init value */
static const TNhtcert_CertGetVersionOutMsg g_certGetVersion_outMsg_default_value =
{
  (TMsgBuf_desc)&g_Nhtcert_CertGetVersionOutMsg_messageDescriptor,/* Base msg descriptor ref */
  NHTCERT_CERT_STATUS_NOERROR,                           /* field: required TNhtcert_CertStatus retStatus */
  0                                                      /* field: required uint32_t            version   */
};

/* Default "TNhtcert_CertGetStringOutMsg" structure init value */
static const TNhtcert_CertGetStringOutMsg g_certGetString_outMsg_default_value =
{
  (TMsgBuf_desc)&g_Nhtcert_CertGetStringOutMsg_messageDescriptor,/* Base msg descriptor ref */
  NHTCERT_CERT_STATUS_NOERROR,                          /* field: required TNhtcert_CertStatus retStatus */
  {0, NULL}                                             /* field: optional TMsgBuf_bytes       name      */
};


/*****************************************************************************
 * message descriptor implementation                                         *
 ****************************************************************************/

/* "g_Nhtcert_EmptyMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtcert_EmptyMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,     /* field:   magicId */
  "Nhtcert_EmptyMsg",                     /* field: * pName */
  "EmptyMsg",                             /* field: * pShortName */
  "Nhtcert_EmptyMsg",                     /* field: * c_name */
  "nhtcert",                              /* field: * pPackageName */
  sizeof(TNhtcert_EmptyMsg),              /* field:   sizeof_message */
  &g_empty_msg_default_value,             /* field:   init value */
  0,                                      /* field:   n_fields */
  NULL,                                   /* field: * pFields */
  &msgbuf_genericMessageInit,             /* field:   message_init */
};

/* "gNhtcert_CertStatusOutMsg_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Nhtcert_CertStatusOutMsg_methodsDescriptor[1] =
{
  {
    "retStatus",                                           /* field: * pName */
    MSGBUF_FIELDTYPE_ENUM,                                 /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                              /* field:   label */
    0,                                                     /* field:   packed */
    1,                                                     /* field:   id */
    sizeof(TNhtcert_CertStatus ),                          /* field:   sizeof_field */
    0,                                                     /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_CertStatusOutMsg,retStatus), /* field:   offset */
    &g_nhtcert_cert_status_enumDescriptor,                 /* field: * pDescriptor */
    NULL                                                   /* field: * pDefaultValue */
  }
};

/* "g_Nhtcert_CertStatusOutMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtcert_CertStatusOutMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,             /* field:   magicId */
  "Nhtcert_CertStatusOutMsg",                     /* field: * pName */
  "CertStatusOutMsg",                             /* field: * pShortName */
  "Nhtcert_CertStatusOutMsg",                     /* field: * c_name */
  "nhtcert",                                      /* field: * pPackageName */
  sizeof(TNhtcert_CertStatusOutMsg),              /* field:   sizeof_message */
  &g_certStatus_outMsg_default_value,             /* field:   init value */
  1,                                              /* field:   n_fields */
  g_Nhtcert_CertStatusOutMsg_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                     /* field:   message_init */
};

/* "gNhtcert_HandleOutMsg_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Nhtcert_HandleOutMsg_methodsDescriptor[2] =
{
  {
    "retStatus",                                       /* field: * pName */
    MSGBUF_FIELDTYPE_ENUM,                             /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                          /* field:   label */
    0,                                                 /* field:   packed */
    1,                                                 /* field:   id */
    sizeof(TNhtcert_CertStatus ),                      /* field:   sizeof_field */
    0,                                                 /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_HandleOutMsg,retStatus), /* field:   offset */
    &g_nhtcert_cert_status_enumDescriptor,             /* field: * pDescriptor */
    NULL                                               /* field: * pDefaultValue */
  },
  {
    "handle",                                           /* field: * pName */
    MSGBUF_FIELDTYPE_INT64,                             /* field:   type */
    MSGBUF_TAGLABEL_OPTIONAL,                           /* field:   label */
    0,                                                  /* field:   packed */
    2,                                                  /* field:   id */
    sizeof(int64_t ),                                   /* field:   sizeof_field */
    MSGBUF_OFFSET_OF(TNhtcert_HandleOutMsg,has_handle), /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_HandleOutMsg,handle),     /* field:   offset */
    NULL,                                               /* field: * pDescriptor */
    NULL                                                /* field: * pDefaultValue */
  }
};

/* "g_Nhtcert_HandleOutMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtcert_HandleOutMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,         /* field:   magicId */
  "Nhtcert_HandleOutMsg",                     /* field: * pName */
  "HandleOutMsg",                             /* field: * pShortName */
  "Nhtcert_HandleOutMsg",                     /* field: * c_name */
  "nhtcert",                                  /* field: * pPackageName */
  sizeof(TNhtcert_HandleOutMsg),              /* field:   sizeof_message */
  &g_handle_outMsg_default_value,             /* field:   init value */
  2,                                          /* field:   n_fields */
  g_Nhtcert_HandleOutMsg_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                 /* field:   message_init */
};

/* "gNhtcert_CertCommandInMsg_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Nhtcert_CertCommandInMsg_methodsDescriptor[3] =
{
  {
    "inputData",                                           /* field: * pName */
    MSGBUF_FIELDTYPE_BYTES,                                /* field:   type */
    MSGBUF_TAGLABEL_OPTIONAL,                              /* field:   label */
    0,                                                     /* field:   packed */
    1,                                                     /* field:   id */
    sizeof(TMsgBuf_bytes ),                                /* field:   sizeof_field */
    0,                                                     /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_CertCommandInMsg,inputData), /* field:   offset */
    NULL,                                                  /* field: * pDescriptor */
    NULL                                                   /* field: * pDefaultValue */
  },
  {
    "opcodes",                                           /* field: * pName */
    MSGBUF_FIELDTYPE_BYTES,                              /* field:   type */
    MSGBUF_TAGLABEL_OPTIONAL,                            /* field:   label */
    0,                                                   /* field:   packed */
    2,                                                   /* field:   id */
    sizeof(TMsgBuf_bytes ),                              /* field:   sizeof_field */
    0,                                                   /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_CertCommandInMsg,opcodes), /* field:   offset */
    NULL,                                                /* field: * pDescriptor */
    NULL                                                 /* field: * pDefaultValue */
  },
  {
    "timeoutType",                                           /* field: * pName */
    MSGBUF_FIELDTYPE_INT32,                                  /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                                /* field:   label */
    0,                                                       /* field:   packed */
    3,                                                       /* field:   id */
    sizeof(int32_t ),                                        /* field:   sizeof_field */
    0,                                                       /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_CertCommandInMsg,timeoutType), /* field:   offset */
    NULL,                                                    /* field: * pDescriptor */
    NULL                                                     /* field: * pDefaultValue */
  }
};

/* "g_Nhtcert_CertCommandInMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtcert_CertCommandInMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,             /* field:   magicId */
  "Nhtcert_CertCommandInMsg",                     /* field: * pName */
  "CertCommandInMsg",                             /* field: * pShortName */
  "Nhtcert_CertCommandInMsg",                     /* field: * c_name */
  "nhtcert",                                      /* field: * pPackageName */
  sizeof(TNhtcert_CertCommandInMsg),              /* field:   sizeof_message */
  &g_certCommand_inMsg_default_value,             /* field:   init value */
  3,                                              /* field:   n_fields */
  g_Nhtcert_CertCommandInMsg_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                     /* field:   message_init */
};

/* "gNhtcert_CertCommandOutMsg_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Nhtcert_CertCommandOutMsg_methodsDescriptor[2] =
{
  {
    "outputData",                                            /* field: * pName */
    MSGBUF_FIELDTYPE_BYTES,                                  /* field:   type */
    MSGBUF_TAGLABEL_OPTIONAL,                                /* field:   label */
    0,                                                       /* field:   packed */
    1,                                                       /* field:   id */
    sizeof(TMsgBuf_bytes ),                                  /* field:   sizeof_field */
    0,                                                       /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_CertCommandOutMsg,outputData), /* field:   offset */
    NULL,                                                    /* field: * pDescriptor */
    NULL                                                     /* field: * pDefaultValue */
  },
  {
    "status",                                            /* field: * pName */
    MSGBUF_FIELDTYPE_BYTES,                              /* field:   type */
    MSGBUF_TAGLABEL_OPTIONAL,                            /* field:   label */
    0,                                                   /* field:   packed */
    2,                                                   /* field:   id */
    sizeof(TMsgBuf_bytes ),                              /* field:   sizeof_field */
    0,                                                   /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_CertCommandOutMsg,status), /* field:   offset */
    NULL,                                                /* field: * pDescriptor */
    NULL                                                 /* field: * pDefaultValue */
  }
};

/* "g_Nhtcert_CertCommandOutMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtcert_CertCommandOutMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,              /* field:   magicId */
  "Nhtcert_CertCommandOutMsg",                     /* field: * pName */
  "CertCommandOutMsg",                             /* field: * pShortName */
  "Nhtcert_CertCommandOutMsg",                     /* field: * c_name */
  "nhtcert",                                       /* field: * pPackageName */
  sizeof(TNhtcert_CertCommandOutMsg),              /* field:   sizeof_message */
  &g_certCommand_outMsg_default_value,             /* field:   init value */
  2,                                               /* field:   n_fields */
  g_Nhtcert_CertCommandOutMsg_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                      /* field:   message_init */
};

/* "gNhtcert_CertTableHandleOutMsg_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Nhtcert_CertTableHandleOutMsg_methodsDescriptor[2] =
{
  {
    "handle",                                                    /* field: * pName */
    MSGBUF_FIELDTYPE_INT64,                                      /* field:   type */
    MSGBUF_TAGLABEL_OPTIONAL,                                    /* field:   label */
    0,                                                           /* field:   packed */
    1,                                                           /* field:   id */
    sizeof(int64_t ),                                            /* field:   sizeof_field */
    MSGBUF_OFFSET_OF(TNhtcert_CertTableHandleOutMsg,has_handle), /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_CertTableHandleOutMsg,handle),     /* field:   offset */
    NULL,                                                        /* field: * pDescriptor */
    NULL                                                         /* field: * pDefaultValue */
  },
  {
    "apiVersion",                                                /* field: * pName */
    MSGBUF_FIELDTYPE_UINT32,                                     /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                                    /* field:   label */
    0,                                                           /* field:   packed */
    2,                                                           /* field:   id */
    sizeof(uint32_t ),                                           /* field:   sizeof_field */
    0,                                                           /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_CertTableHandleOutMsg,apiVersion), /* field:   offset */
    NULL,                                                        /* field: * pDescriptor */
    NULL                                                         /* field: * pDefaultValue */
  }
};

/* "g_Nhtcert_CertTableHandleOutMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtcert_CertTableHandleOutMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,                  /* field:   magicId */
  "Nhtcert_CertTableHandleOutMsg",                     /* field: * pName */
  "CertTableHandleOutMsg",                             /* field: * pShortName */
  "Nhtcert_CertTableHandleOutMsg",                     /* field: * c_name */
  "nhtcert",                                           /* field: * pPackageName */
  sizeof(TNhtcert_CertTableHandleOutMsg),              /* field:   sizeof_message */
  &g_certTableHandle_outMsg_default_value,             /* field:   init value */
  2,                                                   /* field:   n_fields */
  g_Nhtcert_CertTableHandleOutMsg_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                          /* field:   message_init */
};

/* "gNhtcert_CertLockInMsg_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Nhtcert_CertLockInMsg_methodsDescriptor[1] =
{
  {
    "has_output",                                        /* field: * pName */
    MSGBUF_FIELDTYPE_BOOL,                               /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                            /* field:   label */
    0,                                                   /* field:   packed */
    1,                                                   /* field:   id */
    sizeof(TMsgBuf_bool ),                               /* field:   sizeof_field */
    0,                                                   /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_CertLockInMsg,has_output), /* field:   offset */
    NULL,                                                /* field: * pDescriptor */
    NULL                                                 /* field: * pDefaultValue */
  }
};

/* "g_Nhtcert_CertLockInMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtcert_CertLockInMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,          /* field:   magicId */
  "Nhtcert_CertLockInMsg",                     /* field: * pName */
  "CertLockInMsg",                             /* field: * pShortName */
  "Nhtcert_CertLockInMsg",                     /* field: * c_name */
  "nhtcert",                                   /* field: * pPackageName */
  sizeof(TNhtcert_CertLockInMsg),              /* field:   sizeof_message */
  &g_certLock_inMsg_default_value,             /* field:   init value */
  1,                                           /* field:   n_fields */
  g_Nhtcert_CertLockInMsg_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                  /* field:   message_init */
};

/* "gNhtcert_CertUnlockInMsg_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Nhtcert_CertUnlockInMsg_methodsDescriptor[1] =
{
  {
    "resHandle",                                              /* field: * pName */
    MSGBUF_FIELDTYPE_INT64,                                   /* field:   type */
    MSGBUF_TAGLABEL_OPTIONAL,                                 /* field:   label */
    0,                                                        /* field:   packed */
    1,                                                        /* field:   id */
    sizeof(int64_t ),                                         /* field:   sizeof_field */
    MSGBUF_OFFSET_OF(TNhtcert_CertUnlockInMsg,has_resHandle), /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_CertUnlockInMsg,resHandle),     /* field:   offset */
    NULL,                                                     /* field: * pDescriptor */
    NULL                                                      /* field: * pDefaultValue */
  }
};

/* "g_Nhtcert_CertUnlockInMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtcert_CertUnlockInMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,            /* field:   magicId */
  "Nhtcert_CertUnlockInMsg",                     /* field: * pName */
  "CertUnlockInMsg",                             /* field: * pShortName */
  "Nhtcert_CertUnlockInMsg",                     /* field: * c_name */
  "nhtcert",                                     /* field: * pPackageName */
  sizeof(TNhtcert_CertUnlockInMsg),              /* field:   sizeof_message */
  &g_certUnlock_inMsg_default_value,             /* field:   init value */
  1,                                             /* field:   n_fields */
  g_Nhtcert_CertUnlockInMsg_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                    /* field:   message_init */
};

/* "gNhtcert_CertExchangeInMsg_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Nhtcert_CertExchangeInMsg_methodsDescriptor[3] =
{
  {
    "resHandle",                                                /* field: * pName */
    MSGBUF_FIELDTYPE_INT64,                                     /* field:   type */
    MSGBUF_TAGLABEL_OPTIONAL,                                   /* field:   label */
    0,                                                          /* field:   packed */
    1,                                                          /* field:   id */
    sizeof(int64_t ),                                           /* field:   sizeof_field */
    MSGBUF_OFFSET_OF(TNhtcert_CertExchangeInMsg,has_resHandle), /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_CertExchangeInMsg,resHandle),     /* field:   offset */
    NULL,                                                       /* field: * pDescriptor */
    NULL                                                        /* field: * pDefaultValue */
  },
  {
    "certCommands",                                              /* field: * pName */
    MSGBUF_FIELDTYPE_MESSAGE,                                    /* field:   type */
    MSGBUF_TAGLABEL_REPEATED,                                    /* field:   label */
    0,                                                           /* field:   packed */
    2,                                                           /* field:   id */
    sizeof(TNhtcert_CertCommandInMsg*),                          /* field:   sizeof_field */
    MSGBUF_OFFSET_OF(TNhtcert_CertExchangeInMsg,n_certCommands), /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_CertExchangeInMsg,certCommands),   /* field:   offset */
    &g_Nhtcert_CertCommandInMsg_messageDescriptor,               /* field: * pDescriptor */
    NULL                                                         /* field: * pDefaultValue */
  },
  {
    "hasProcessedCmdSize",                                            /* field: * pName */
    MSGBUF_FIELDTYPE_BOOL,                                            /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                                         /* field:   label */
    0,                                                                /* field:   packed */
    3,                                                                /* field:   id */
    sizeof(TMsgBuf_bool ),                                            /* field:   sizeof_field */
    0,                                                                /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_CertExchangeInMsg,hasProcessedCmdSize), /* field:   offset */
    NULL,                                                             /* field: * pDescriptor */
    NULL                                                              /* field: * pDefaultValue */
  }
};

/* "g_Nhtcert_CertExchangeInMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtcert_CertExchangeInMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,              /* field:   magicId */
  "Nhtcert_CertExchangeInMsg",                     /* field: * pName */
  "CertExchangeInMsg",                             /* field: * pShortName */
  "Nhtcert_CertExchangeInMsg",                     /* field: * c_name */
  "nhtcert",                                       /* field: * pPackageName */
  sizeof(TNhtcert_CertExchangeInMsg),              /* field:   sizeof_message */
  &g_certExchange_inMsg_default_value,             /* field:   init value */
  3,                                               /* field:   n_fields */
  g_Nhtcert_CertExchangeInMsg_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                      /* field:   message_init */
};

/* "gNhtcert_CertExchangeOutMsg_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Nhtcert_CertExchangeOutMsg_methodsDescriptor[3] =
{
  {
    "retStatus",                                             /* field: * pName */
    MSGBUF_FIELDTYPE_ENUM,                                   /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                                /* field:   label */
    0,                                                       /* field:   packed */
    1,                                                       /* field:   id */
    sizeof(TNhtcert_CertStatus ),                            /* field:   sizeof_field */
    0,                                                       /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_CertExchangeOutMsg,retStatus), /* field:   offset */
    &g_nhtcert_cert_status_enumDescriptor,                   /* field: * pDescriptor */
    NULL                                                     /* field: * pDefaultValue */
  },
  {
    "processedCmds",                                             /* field: * pName */
    MSGBUF_FIELDTYPE_UINT32,                                     /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                                    /* field:   label */
    0,                                                           /* field:   packed */
    2,                                                           /* field:   id */
    sizeof(uint32_t ),                                           /* field:   sizeof_field */
    0,                                                           /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_CertExchangeOutMsg,processedCmds), /* field:   offset */
    NULL,                                                        /* field: * pDescriptor */
    NULL                                                         /* field: * pDefaultValue */
  },
  {
    "certCommands",                                               /* field: * pName */
    MSGBUF_FIELDTYPE_MESSAGE,                                     /* field:   type */
    MSGBUF_TAGLABEL_REPEATED,                                     /* field:   label */
    0,                                                            /* field:   packed */
    3,                                                            /* field:   id */
    sizeof(TNhtcert_CertCommandOutMsg*),                          /* field:   sizeof_field */
    MSGBUF_OFFSET_OF(TNhtcert_CertExchangeOutMsg,n_certCommands), /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_CertExchangeOutMsg,certCommands),   /* field:   offset */
    &g_Nhtcert_CertCommandOutMsg_messageDescriptor,               /* field: * pDescriptor */
    NULL                                                          /* field: * pDefaultValue */
  }
};

/* "g_Nhtcert_CertExchangeOutMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtcert_CertExchangeOutMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,               /* field:   magicId */
  "Nhtcert_CertExchangeOutMsg",                     /* field: * pName */
  "CertExchangeOutMsg",                             /* field: * pShortName */
  "Nhtcert_CertExchangeOutMsg",                     /* field: * c_name */
  "nhtcert",                                        /* field: * pPackageName */
  sizeof(TNhtcert_CertExchangeOutMsg),              /* field:   sizeof_message */
  &g_certExchange_outMsg_default_value,             /* field:   init value */
  3,                                                /* field:   n_fields */
  g_Nhtcert_CertExchangeOutMsg_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                       /* field:   message_init */
};

/* "gNhtcert_CertGetSingleInfoInMsg_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Nhtcert_CertGetSingleInfoInMsg_methodsDescriptor[1] =
{
  {
    "has_output",                                                 /* field: * pName */
    MSGBUF_FIELDTYPE_BOOL,                                        /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                                     /* field:   label */
    0,                                                            /* field:   packed */
    1,                                                            /* field:   id */
    sizeof(TMsgBuf_bool ),                                        /* field:   sizeof_field */
    0,                                                            /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_CertGetSingleInfoInMsg,has_output), /* field:   offset */
    NULL,                                                         /* field: * pDescriptor */
    NULL                                                          /* field: * pDefaultValue */
  }
};

/* "g_Nhtcert_CertGetSingleInfoInMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtcert_CertGetSingleInfoInMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,                   /* field:   magicId */
  "Nhtcert_CertGetSingleInfoInMsg",                     /* field: * pName */
  "CertGetSingleInfoInMsg",                             /* field: * pShortName */
  "Nhtcert_CertGetSingleInfoInMsg",                     /* field: * c_name */
  "nhtcert",                                            /* field: * pPackageName */
  sizeof(TNhtcert_CertGetSingleInfoInMsg),              /* field:   sizeof_message */
  &g_certGetSingleInfo_inMsg_default_value,             /* field:   init value */
  1,                                                    /* field:   n_fields */
  g_Nhtcert_CertGetSingleInfoInMsg_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                           /* field:   message_init */
};

/* "gNhtcert_CertGetVersionOutMsg_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Nhtcert_CertGetVersionOutMsg_methodsDescriptor[2] =
{
  {
    "retStatus",                                               /* field: * pName */
    MSGBUF_FIELDTYPE_ENUM,                                     /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                                  /* field:   label */
    0,                                                         /* field:   packed */
    1,                                                         /* field:   id */
    sizeof(TNhtcert_CertStatus ),                              /* field:   sizeof_field */
    0,                                                         /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_CertGetVersionOutMsg,retStatus), /* field:   offset */
    &g_nhtcert_cert_status_enumDescriptor,                     /* field: * pDescriptor */
    NULL                                                       /* field: * pDefaultValue */
  },
  {
    "version",                                               /* field: * pName */
    MSGBUF_FIELDTYPE_UINT32,                                 /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                                /* field:   label */
    0,                                                       /* field:   packed */
    2,                                                       /* field:   id */
    sizeof(uint32_t ),                                       /* field:   sizeof_field */
    0,                                                       /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_CertGetVersionOutMsg,version), /* field:   offset */
    NULL,                                                    /* field: * pDescriptor */
    NULL                                                     /* field: * pDefaultValue */
  }
};

/* "g_Nhtcert_CertGetVersionOutMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtcert_CertGetVersionOutMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,                 /* field:   magicId */
  "Nhtcert_CertGetVersionOutMsg",                     /* field: * pName */
  "CertGetVersionOutMsg",                             /* field: * pShortName */
  "Nhtcert_CertGetVersionOutMsg",                     /* field: * c_name */
  "nhtcert",                                          /* field: * pPackageName */
  sizeof(TNhtcert_CertGetVersionOutMsg),              /* field:   sizeof_message */
  &g_certGetVersion_outMsg_default_value,             /* field:   init value */
  2,                                                  /* field:   n_fields */
  g_Nhtcert_CertGetVersionOutMsg_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                         /* field:   message_init */
};

/* "gNhtcert_CertGetStringOutMsg_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Nhtcert_CertGetStringOutMsg_methodsDescriptor[2] =
{
  {
    "retStatus",                                              /* field: * pName */
    MSGBUF_FIELDTYPE_ENUM,                                    /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                                 /* field:   label */
    0,                                                        /* field:   packed */
    1,                                                        /* field:   id */
    sizeof(TNhtcert_CertStatus ),                             /* field:   sizeof_field */
    0,                                                        /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_CertGetStringOutMsg,retStatus), /* field:   offset */
    &g_nhtcert_cert_status_enumDescriptor,                    /* field: * pDescriptor */
    NULL                                                      /* field: * pDefaultValue */
  },
  {
    "name",                                              /* field: * pName */
    MSGBUF_FIELDTYPE_BYTES,                              /* field:   type */
    MSGBUF_TAGLABEL_OPTIONAL,                            /* field:   label */
    0,                                                   /* field:   packed */
    2,                                                   /* field:   id */
    sizeof(TMsgBuf_bytes ),                              /* field:   sizeof_field */
    0,                                                   /* field:   qoffset */
    MSGBUF_OFFSET_OF(TNhtcert_CertGetStringOutMsg,name), /* field:   offset */
    NULL,                                                /* field: * pDescriptor */
    NULL                                                 /* field: * pDefaultValue */
  }
};

/* "g_Nhtcert_CertGetStringOutMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Nhtcert_CertGetStringOutMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,                /* field:   magicId */
  "Nhtcert_CertGetStringOutMsg",                     /* field: * pName */
  "CertGetStringOutMsg",                             /* field: * pShortName */
  "Nhtcert_CertGetStringOutMsg",                     /* field: * c_name */
  "nhtcert",                                         /* field: * pPackageName */
  sizeof(TNhtcert_CertGetStringOutMsg),              /* field:   sizeof_message */
  &g_certGetString_outMsg_default_value,             /* field:   init value */
  2,                                                 /* field:   n_fields */
  g_Nhtcert_CertGetStringOutMsg_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                        /* field:   message_init */
};


/*****************************************************************************
 * message init implementation                                               *
 ****************************************************************************/

/* init_Nhtcert_EmptyMsg function implementation */
void init_Nhtcert_EmptyMsg ( TNhtcert_EmptyMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtcert_EmptyMsg_messageDescriptor); }

/* init_Nhtcert_CertStatusOutMsg function implementation */
void init_Nhtcert_CertStatusOutMsg ( TNhtcert_CertStatusOutMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtcert_CertStatusOutMsg_messageDescriptor); }

/* init_Nhtcert_HandleOutMsg function implementation */
void init_Nhtcert_HandleOutMsg ( TNhtcert_HandleOutMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtcert_HandleOutMsg_messageDescriptor); }

/* init_Nhtcert_CertCommandInMsg function implementation */
void init_Nhtcert_CertCommandInMsg ( TNhtcert_CertCommandInMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtcert_CertCommandInMsg_messageDescriptor); }

/* init_Nhtcert_CertCommandOutMsg function implementation */
void init_Nhtcert_CertCommandOutMsg ( TNhtcert_CertCommandOutMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtcert_CertCommandOutMsg_messageDescriptor); }

/* init_Nhtcert_CertTableHandleOutMsg function implementation */
void init_Nhtcert_CertTableHandleOutMsg ( TNhtcert_CertTableHandleOutMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtcert_CertTableHandleOutMsg_messageDescriptor); }

/* init_Nhtcert_CertLockInMsg function implementation */
void init_Nhtcert_CertLockInMsg ( TNhtcert_CertLockInMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtcert_CertLockInMsg_messageDescriptor); }

/* init_Nhtcert_CertUnlockInMsg function implementation */
void init_Nhtcert_CertUnlockInMsg ( TNhtcert_CertUnlockInMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtcert_CertUnlockInMsg_messageDescriptor); }

/* init_Nhtcert_CertExchangeInMsg function implementation */
void init_Nhtcert_CertExchangeInMsg ( TNhtcert_CertExchangeInMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtcert_CertExchangeInMsg_messageDescriptor); }

/* init_Nhtcert_CertExchangeOutMsg function implementation */
void init_Nhtcert_CertExchangeOutMsg ( TNhtcert_CertExchangeOutMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtcert_CertExchangeOutMsg_messageDescriptor); }

/* init_Nhtcert_CertGetSingleInfoInMsg function implementation */
void init_Nhtcert_CertGetSingleInfoInMsg ( TNhtcert_CertGetSingleInfoInMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtcert_CertGetSingleInfoInMsg_messageDescriptor); }

/* init_Nhtcert_CertGetVersionOutMsg function implementation */
void init_Nhtcert_CertGetVersionOutMsg ( TNhtcert_CertGetVersionOutMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtcert_CertGetVersionOutMsg_messageDescriptor); }

/* init_Nhtcert_CertGetStringOutMsg function implementation */
void init_Nhtcert_CertGetStringOutMsg ( TNhtcert_CertGetStringOutMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Nhtcert_CertGetStringOutMsg_messageDescriptor); }


/*****************************************************************************
 * message alloc implementation                                              *
 ****************************************************************************/

/* pAlloc_Nhtcert_EmptyMsg function implementation */
TNhtcert_EmptyMsg * pAlloc_Nhtcert_EmptyMsg ()
{
  TNhtcert_EmptyMsg * pNewInstance;
  pNewInstance = (TNhtcert_EmptyMsg*)MSGBUF_SYS_malloc(sizeof(TNhtcert_EmptyMsg));
  init_Nhtcert_EmptyMsg (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Nhtcert_CertStatusOutMsg function implementation */
TNhtcert_CertStatusOutMsg * pAlloc_Nhtcert_CertStatusOutMsg ()
{
  TNhtcert_CertStatusOutMsg * pNewInstance;
  pNewInstance = (TNhtcert_CertStatusOutMsg*)MSGBUF_SYS_malloc(sizeof(TNhtcert_CertStatusOutMsg));
  init_Nhtcert_CertStatusOutMsg (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Nhtcert_HandleOutMsg function implementation */
TNhtcert_HandleOutMsg * pAlloc_Nhtcert_HandleOutMsg ()
{
  TNhtcert_HandleOutMsg * pNewInstance;
  pNewInstance = (TNhtcert_HandleOutMsg*)MSGBUF_SYS_malloc(sizeof(TNhtcert_HandleOutMsg));
  init_Nhtcert_HandleOutMsg (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Nhtcert_CertCommandInMsg function implementation */
TNhtcert_CertCommandInMsg * pAlloc_Nhtcert_CertCommandInMsg ()
{
  TNhtcert_CertCommandInMsg * pNewInstance;
  pNewInstance = (TNhtcert_CertCommandInMsg*)MSGBUF_SYS_malloc(sizeof(TNhtcert_CertCommandInMsg));
  init_Nhtcert_CertCommandInMsg (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Nhtcert_CertCommandOutMsg function implementation */
TNhtcert_CertCommandOutMsg * pAlloc_Nhtcert_CertCommandOutMsg ()
{
  TNhtcert_CertCommandOutMsg * pNewInstance;
  pNewInstance = (TNhtcert_CertCommandOutMsg*)MSGBUF_SYS_malloc(sizeof(TNhtcert_CertCommandOutMsg));
  init_Nhtcert_CertCommandOutMsg (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Nhtcert_CertTableHandleOutMsg function implementation */
TNhtcert_CertTableHandleOutMsg * pAlloc_Nhtcert_CertTableHandleOutMsg ()
{
  TNhtcert_CertTableHandleOutMsg * pNewInstance;
  pNewInstance = (TNhtcert_CertTableHandleOutMsg*)MSGBUF_SYS_malloc(sizeof(TNhtcert_CertTableHandleOutMsg));
  init_Nhtcert_CertTableHandleOutMsg (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Nhtcert_CertLockInMsg function implementation */
TNhtcert_CertLockInMsg * pAlloc_Nhtcert_CertLockInMsg ()
{
  TNhtcert_CertLockInMsg * pNewInstance;
  pNewInstance = (TNhtcert_CertLockInMsg*)MSGBUF_SYS_malloc(sizeof(TNhtcert_CertLockInMsg));
  init_Nhtcert_CertLockInMsg (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Nhtcert_CertUnlockInMsg function implementation */
TNhtcert_CertUnlockInMsg * pAlloc_Nhtcert_CertUnlockInMsg ()
{
  TNhtcert_CertUnlockInMsg * pNewInstance;
  pNewInstance = (TNhtcert_CertUnlockInMsg*)MSGBUF_SYS_malloc(sizeof(TNhtcert_CertUnlockInMsg));
  init_Nhtcert_CertUnlockInMsg (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Nhtcert_CertExchangeInMsg function implementation */
TNhtcert_CertExchangeInMsg * pAlloc_Nhtcert_CertExchangeInMsg ()
{
  TNhtcert_CertExchangeInMsg * pNewInstance;
  pNewInstance = (TNhtcert_CertExchangeInMsg*)MSGBUF_SYS_malloc(sizeof(TNhtcert_CertExchangeInMsg));
  init_Nhtcert_CertExchangeInMsg (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Nhtcert_CertExchangeOutMsg function implementation */
TNhtcert_CertExchangeOutMsg * pAlloc_Nhtcert_CertExchangeOutMsg ()
{
  TNhtcert_CertExchangeOutMsg * pNewInstance;
  pNewInstance = (TNhtcert_CertExchangeOutMsg*)MSGBUF_SYS_malloc(sizeof(TNhtcert_CertExchangeOutMsg));
  init_Nhtcert_CertExchangeOutMsg (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Nhtcert_CertGetSingleInfoInMsg function implementation */
TNhtcert_CertGetSingleInfoInMsg * pAlloc_Nhtcert_CertGetSingleInfoInMsg ()
{
  TNhtcert_CertGetSingleInfoInMsg * pNewInstance;
  pNewInstance = (TNhtcert_CertGetSingleInfoInMsg*)MSGBUF_SYS_malloc(sizeof(TNhtcert_CertGetSingleInfoInMsg));
  init_Nhtcert_CertGetSingleInfoInMsg (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Nhtcert_CertGetVersionOutMsg function implementation */
TNhtcert_CertGetVersionOutMsg * pAlloc_Nhtcert_CertGetVersionOutMsg ()
{
  TNhtcert_CertGetVersionOutMsg * pNewInstance;
  pNewInstance = (TNhtcert_CertGetVersionOutMsg*)MSGBUF_SYS_malloc(sizeof(TNhtcert_CertGetVersionOutMsg));
  init_Nhtcert_CertGetVersionOutMsg (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Nhtcert_CertGetStringOutMsg function implementation */
TNhtcert_CertGetStringOutMsg * pAlloc_Nhtcert_CertGetStringOutMsg ()
{
  TNhtcert_CertGetStringOutMsg * pNewInstance;
  pNewInstance = (TNhtcert_CertGetStringOutMsg*)MSGBUF_SYS_malloc(sizeof(TNhtcert_CertGetStringOutMsg));
  init_Nhtcert_CertGetStringOutMsg (pNewInstance);
  return pNewInstance;
}


/*****************************************************************************
 * message dealloc implementation                                            *
 ****************************************************************************/

/* dealloc_Nhtcert_EmptyMsg function implementation */
void dealloc_Nhtcert_EmptyMsg (TNhtcert_EmptyMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Nhtcert_CertStatusOutMsg function implementation */
void dealloc_Nhtcert_CertStatusOutMsg (TNhtcert_CertStatusOutMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Nhtcert_HandleOutMsg function implementation */
void dealloc_Nhtcert_HandleOutMsg (TNhtcert_HandleOutMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Nhtcert_CertCommandInMsg function implementation */
void dealloc_Nhtcert_CertCommandInMsg (TNhtcert_CertCommandInMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Nhtcert_CertCommandOutMsg function implementation */
void dealloc_Nhtcert_CertCommandOutMsg (TNhtcert_CertCommandOutMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Nhtcert_CertTableHandleOutMsg function implementation */
void dealloc_Nhtcert_CertTableHandleOutMsg (TNhtcert_CertTableHandleOutMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Nhtcert_CertLockInMsg function implementation */
void dealloc_Nhtcert_CertLockInMsg (TNhtcert_CertLockInMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Nhtcert_CertUnlockInMsg function implementation */
void dealloc_Nhtcert_CertUnlockInMsg (TNhtcert_CertUnlockInMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Nhtcert_CertExchangeInMsg function implementation */
void dealloc_Nhtcert_CertExchangeInMsg (TNhtcert_CertExchangeInMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Nhtcert_CertExchangeOutMsg function implementation */
void dealloc_Nhtcert_CertExchangeOutMsg (TNhtcert_CertExchangeOutMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Nhtcert_CertGetSingleInfoInMsg function implementation */
void dealloc_Nhtcert_CertGetSingleInfoInMsg (TNhtcert_CertGetSingleInfoInMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Nhtcert_CertGetVersionOutMsg function implementation */
void dealloc_Nhtcert_CertGetVersionOutMsg (TNhtcert_CertGetVersionOutMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Nhtcert_CertGetStringOutMsg function implementation */
void dealloc_Nhtcert_CertGetStringOutMsg (TNhtcert_CertGetStringOutMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }


/*****************************************************************************
 * msgbuf enum test function implementation                                  *
 ****************************************************************************/

int isValid_Nhtcert_CertStatus (TNhtcert_CertStatus xValue)
{
  return msgbuf_genericTestEnum (&g_nhtcert_cert_status_enumDescriptor, (int)xValue);
}

int isValid_Nhtcert_TimeoutType (TNhtcert_TimeoutType xValue)
{
  return msgbuf_genericTestEnum (&g_nhtcert_timeout_type_enumDescriptor, (int)xValue);
}


/*****************************************************************************
 * service descriptor implementation                                         *
 ****************************************************************************/

static const TMsgBuf_methodDescriptor g_nhtcert_v1_0_1_serviceMethodsDescriptor[6] =
{
  /* 'hc_nht_getFunctionTable' method descriptor (index=0) */
  {
    "hc_nht_getFunctionTable",
    &g_Nhtcert_EmptyMsg_messageDescriptor,
    &g_Nhtcert_CertTableHandleOutMsg_messageDescriptor,
    (TMsgBuf_rpcFctEntry)&rpc_nhtcert_hc_nht_getFunctionTable
  },
  /* 'hc_nht_getDriverVersion' method descriptor (index=1) */
  {
    "hc_nht_getDriverVersion",
    &g_Nhtcert_CertGetSingleInfoInMsg_messageDescriptor,
    &g_Nhtcert_CertGetVersionOutMsg_messageDescriptor,
    (TMsgBuf_rpcFctEntry)&rpc_nhtcert_hc_nht_getDriverVersion
  },
  /* 'hc_nht_getServiceName' method descriptor (index=2) */
  {
    "hc_nht_getServiceName",
    &g_Nhtcert_CertGetSingleInfoInMsg_messageDescriptor,
    &g_Nhtcert_CertGetStringOutMsg_messageDescriptor,
    (TMsgBuf_rpcFctEntry)&rpc_nhtcert_hc_nht_getServiceName
  },
  /* 'hc_nht_lock' method descriptor (index=3) */
  {
    "hc_nht_lock",
    &g_Nhtcert_CertLockInMsg_messageDescriptor,
    &g_Nhtcert_HandleOutMsg_messageDescriptor,
    (TMsgBuf_rpcFctEntry)&rpc_nhtcert_hc_nht_lock
  },
  /* 'hc_nht_unlock' method descriptor (index=4) */
  {
    "hc_nht_unlock",
    &g_Nhtcert_CertUnlockInMsg_messageDescriptor,
    &g_Nhtcert_CertStatusOutMsg_messageDescriptor,
    (TMsgBuf_rpcFctEntry)&rpc_nhtcert_hc_nht_unlock
  },
  /* 'hc_nht_exchange' method descriptor (index=5) */
  {
    "hc_nht_exchange",
    &g_Nhtcert_CertExchangeInMsg_messageDescriptor,
    &g_Nhtcert_CertExchangeOutMsg_messageDescriptor,
    (TMsgBuf_rpcFctEntry)&rpc_nhtcert_hc_nht_exchange
  }
};

const TMsgBuf_serviceDescriptor g_nhtcert_v1_0_1_serviceDescriptor =
{
  MSGBUF_SERVICE_DESCRIPTOR_MAGIC_ID,        /* field:   magic */
  "nhtcert_v1_0_1",                          /* field: * pServiceName */
  "nhtcert",                                 /* field: * pPackageName */
  0,                                         /* field:   methodId */
  6,                                         /* field:   n_methods */
  g_nhtcert_v1_0_1_serviceMethodsDescriptor, /* field: * pMethods */
};

