/* DO NOT EDIT THIS FILE!!!
 * This file was automatically generated by msgbuf compiler!
 *
 * This file contains the msgbuf structure definitions associated
 * to the package nhtcert.proto
 */

#ifndef __MSGBUF_EXPORT_NHTCERT_H_
#define __MSGBUF_EXPORT_NHTCERT_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*****************************************************************************
 * include files                                                             *
 ****************************************************************************/


#include "inc/xsd-c.h"
#include "src/msgbuf_nhtcert.h"



/*****************************************************************************
 * message descriptor prototype                                              *
 ****************************************************************************/

extern const TMsgBuf_messageDescriptor g_Nhtcert_EmptyMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtcert_CertStatusOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtcert_HandleOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtcert_CertCommandInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtcert_CertCommandOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtcert_CertTableHandleOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtcert_CertLockInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtcert_CertUnlockInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtcert_CertExchangeInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtcert_CertExchangeOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtcert_CertGetSingleInfoInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtcert_CertGetVersionOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtcert_CertGetStringOutMsg_messageDescriptor;

/*****************************************************************************
 * enum descriptor prototype                                                 *
 ****************************************************************************/

extern const TMsgBuf_enumDescriptor g_nhtcert_cert_status_enumDescriptor;
extern const TMsgBuf_enumDescriptor g_nhtcert_timeout_type_enumDescriptor;

/*****************************************************************************
 * service descriptor prototype                                              *
 ****************************************************************************/

extern const TMsgBuf_serviceDescriptor g_nhtcert_v1_0_1_serviceDescriptor;

#ifdef __cplusplus
}
#endif /* __cplusplus */


#endif /* __MSGBUF_EXPORT_NHTCERT_H_ */
