/* DO NOT EDIT THIS FILE!!!
 * This file was automatically generated by msgbuf compiler!
 *
 * This file contains the msgbuf structure definitions associated
 * to the package nhtcert.proto
 */


/*****************************************************************************
 * include files                                                             *
 ****************************************************************************/

#include "inc/rpc_nhtcert.h"
#include "src/rpc_nhtcert_api.h"
#include "src/_msgbuf_nhtcert.h"



/*****************************************************************************
 * RPC service remote API implementation                                     *
 ****************************************************************************/

