/* DO NOT EDIT THIS FILE!!!
 * This file was automatically generated by msgbuf compiler!
 *
 * This file contains the msgbuf structure definitions associated
 * to the package nhtcsd.proto
 */


/*****************************************************************************
 * include files                                                             *
 ****************************************************************************/

#include "inc/rpc_nhtcsd.h"
#include "src/rpc_nhtcsd_api.h"
#include "src/_msgbuf_nhtcsd.h"



/*****************************************************************************
 * RPC service remote API implementation                                     *
 ****************************************************************************/

/* RPC method: rpc_nhtcsd_tn_ecmCallBack
 *
 * This method stands as an asynchronous notification function.
 * Caller of this function immediately returns without waiting
 * the completion of its remote execution.
 *
 * PS: param 'pxOutputMessage' is always assumed to be NULL.
 */
TRpc_status rpc_nhtcsd_tn_ecmCallBack
(
  TMsgBuf_rpcHandler                xRpcHandler,
  const TNhtcsd_EcmCallBackInMsg  * pxInputMessage,
  TNhtcsd_EmptyMsg               ** pxOutputMessage
)
{
  return rpc_notify (
    xRpcHandler,
    (TMsgBuf_message const *)pxInputMessage,
    gRpcServiceHandle_nhtcsd,
    56 );
}

