/* DO NOT EDIT THIS FILE!!!
 * This file was automatically generated by msgbuf compiler!
 *
 * This file contains the msgbuf structure definitions associated
 * to the package nhtctd.proto
 */

#ifndef __MSGBUF_EXPORT_NHTCTD_H_
#define __MSGBUF_EXPORT_NHTCTD_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*****************************************************************************
 * include files                                                             *
 ****************************************************************************/


#include "inc/xsd-c.h"
#include "src/msgbuf_nhtctd.h"



/*****************************************************************************
 * message descriptor prototype                                              *
 ****************************************************************************/

extern const TMsgBuf_messageDescriptor g_Nhtctd_EmptyMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_IntValueInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_IntValueOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_OptOutput1InMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_CtdStatusOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_BooleanOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_StringOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_GetFlashSizeInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_GetRamSizeInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_MemorySizeOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_FlashReadInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_FlashWriteInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_RamReadInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_RamWriteInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_BytesOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_GetPvStatusInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_GetBufferSizeInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_GetOtpValueMaskInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_SetPvValueInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_SetOtpValueInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_GetPvValueInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_GetHandleInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_HandleOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_HandleInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_PvDescriptorMessage_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_GetPvDescriptorSetInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_GetPvDescriptorSetOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_R2rSetProtectedKeysInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_R2rSessionCipheringInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_EcmCallBackInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_DscSessionParamsMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_OpenDscSessionInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_WaitOnCsdSessionCompletionInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_SetDscProtectedKeysInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_ScrSessionParamsMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_OpenScrSessionInMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Nhtctd_SetScrProtectedKeysInMsg_messageDescriptor;

/*****************************************************************************
 * enum descriptor prototype                                                 *
 ****************************************************************************/


/*****************************************************************************
 * service descriptor prototype                                              *
 ****************************************************************************/

extern const TMsgBuf_serviceDescriptor g_nhtctd_v1_0_1_serviceDescriptor;

#ifdef __cplusplus
}
#endif /* __cplusplus */


#endif /* __MSGBUF_EXPORT_NHTCTD_H_ */
