/* DO NOT EDIT THIS FILE!!!
 * This file was automatically generated by msgbuf compiler!
 *
 * This file contains the msgbuf structure definitions associated
 * to the package nhtcert.proto
 */

#ifndef _RPC_NHTCERT_H_
#define _RPC_NHTCERT_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*****************************************************************************
 * include files                                                             *
 ****************************************************************************/

#include "inc/msgbuf_types.h"



/*****************************************************************************
 * RPC service handle reference                                              *
 ****************************************************************************/

extern const TMsgBuf_serviceHandle gRpcServiceHandle_nhtcert;


#ifdef __cplusplus
}
#endif /* __cplusplus */


#endif /* _RPC_NHTCERT_H_ */
