/* DO NOT EDIT THIS FILE!!!
 * This file was automatically generated by msgbuf compiler!
 *
 * This file contains the msgbuf structure definitions associated
 * to the package rpcctrl.proto
 */

#ifndef __MSGBUF_EXPORT_RPCCTRL_H_
#define __MSGBUF_EXPORT_RPCCTRL_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*****************************************************************************
 * include files                                                             *
 ****************************************************************************/


#include "inc/xsd-c.h"
#include "src/msgbuf_rpcctrl.h"



/*****************************************************************************
 * message descriptor prototype                                              *
 ****************************************************************************/

extern const TMsgBuf_messageDescriptor g_Rpcctrl_RpcServiceDescriptor_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Rpcctrl_RpcServiceDescSetOutMsg_messageDescriptor;
extern const TMsgBuf_messageDescriptor g_Rpcctrl_EmptyMsg_messageDescriptor;

/*****************************************************************************
 * enum descriptor prototype                                                 *
 ****************************************************************************/


/*****************************************************************************
 * service descriptor prototype                                              *
 ****************************************************************************/

extern const TMsgBuf_serviceDescriptor g_rpcctrl_v1_0_1_serviceDescriptor;

#ifdef __cplusplus
}
#endif /* __cplusplus */


#endif /* __MSGBUF_EXPORT_RPCCTRL_H_ */
