/* DO NOT EDIT THIS FILE!!!
 * This file was automatically generated by msgbuf compiler!
 *
 * This file contains the msgbuf structure definitions associated
 * to the package rpcctrl.proto
 */


/*****************************************************************************
 * include files                                                             *
 ****************************************************************************/

#include "inc/msgbuf_sys_malloc.h"
#include <stddef.h>
#include "src/msgbuf_rpcctrl.h"
#include "inc/rpc_rpcctrl.h"
#include "src/_msgbuf_rpcctrl.h"
#include "src/rpc_rpcctrl_api.h"


/*****************************************************************************
 * public rpc service handle                                                 *
 ****************************************************************************/

const TMsgBuf_serviceHandle gRpcServiceHandle_rpcctrl = (TMsgBuf_serviceHandle)&g_rpcctrl_v1_0_1_serviceDescriptor;


/*****************************************************************************
 * nested message descriptor prototype                                       *
 ****************************************************************************/


/*****************************************************************************
 * Generate default value implementation                                     *
 ****************************************************************************/


/*****************************************************************************
 * enum descriptor implementation                                            *
 ****************************************************************************/


/*****************************************************************************
 * message descriptor static init implementation                             *
 ****************************************************************************/

/* Default "TRpcctrl_RpcServiceDescriptor" structure init value */
static const TRpcctrl_RpcServiceDescriptor g_rpcServiceDescriptor_default_value =
{
  (TMsgBuf_desc)&g_Rpcctrl_RpcServiceDescriptor_messageDescriptor,/* Base msg descriptor ref */
  0,                                                    /* field: required uint32_t serviceIdx  */
  NULL,                                                 /* field: optional char     packageName */
  NULL                                                  /* field: optional char     serviceName */
};

/* Default "TRpcctrl_RpcServiceDescSetOutMsg" structure init value */
static const TRpcctrl_RpcServiceDescSetOutMsg g_rpcServiceDescSet_outMsg_default_value =
{
  (TMsgBuf_desc)&g_Rpcctrl_RpcServiceDescSetOutMsg_messageDescriptor,/* Base msg descriptor ref */
  0, NULL                                                   /* field: repeated TRpcctrl_RpcServiceDescriptor serviceDesc */
};

/* Default "TRpcctrl_EmptyMsg" structure init value */
static const TRpcctrl_EmptyMsg g_empty_msg_default_value =
{
  (TMsgBuf_desc)&g_Rpcctrl_EmptyMsg_messageDescriptor,/* Base msg descriptor ref */
};


/*****************************************************************************
 * message descriptor implementation                                         *
 ****************************************************************************/

/* "gRpcctrl_RpcServiceDescriptor_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Rpcctrl_RpcServiceDescriptor_methodsDescriptor[3] =
{
  {
    "serviceIdx",                                               /* field: * pName */
    MSGBUF_FIELDTYPE_UINT32,                                    /* field:   type */
    MSGBUF_TAGLABEL_REQUIRED,                                   /* field:   label */
    0,                                                          /* field:   packed */
    1,                                                          /* field:   id */
    sizeof(uint32_t ),                                          /* field:   sizeof_field */
    0,                                                          /* field:   qoffset */
    MSGBUF_OFFSET_OF(TRpcctrl_RpcServiceDescriptor,serviceIdx), /* field:   offset */
    NULL,                                                       /* field: * pDescriptor */
    NULL                                                        /* field: * pDefaultValue */
  },
  {
    "packageName",                                               /* field: * pName */
    MSGBUF_FIELDTYPE_STRING,                                     /* field:   type */
    MSGBUF_TAGLABEL_OPTIONAL,                                    /* field:   label */
    0,                                                           /* field:   packed */
    2,                                                           /* field:   id */
    sizeof(char*),                                               /* field:   sizeof_field */
    0,                                                           /* field:   qoffset */
    MSGBUF_OFFSET_OF(TRpcctrl_RpcServiceDescriptor,packageName), /* field:   offset */
    NULL,                                                        /* field: * pDescriptor */
    NULL                                                         /* field: * pDefaultValue */
  },
  {
    "serviceName",                                               /* field: * pName */
    MSGBUF_FIELDTYPE_STRING,                                     /* field:   type */
    MSGBUF_TAGLABEL_OPTIONAL,                                    /* field:   label */
    0,                                                           /* field:   packed */
    3,                                                           /* field:   id */
    sizeof(char*),                                               /* field:   sizeof_field */
    0,                                                           /* field:   qoffset */
    MSGBUF_OFFSET_OF(TRpcctrl_RpcServiceDescriptor,serviceName), /* field:   offset */
    NULL,                                                        /* field: * pDescriptor */
    NULL                                                         /* field: * pDefaultValue */
  }
};

/* "g_Rpcctrl_RpcServiceDescriptor_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Rpcctrl_RpcServiceDescriptor_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,                 /* field:   magicId */
  "Rpcctrl_RpcServiceDescriptor",                     /* field: * pName */
  "RpcServiceDescriptor",                             /* field: * pShortName */
  "Rpcctrl_RpcServiceDescriptor",                     /* field: * c_name */
  "rpcctrl",                                          /* field: * pPackageName */
  sizeof(TRpcctrl_RpcServiceDescriptor),              /* field:   sizeof_message */
  &g_rpcServiceDescriptor_default_value,              /* field:   init value */
  3,                                                  /* field:   n_fields */
  g_Rpcctrl_RpcServiceDescriptor_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                         /* field:   message_init */
};

/* "gRpcctrl_RpcServiceDescSetOutMsg_field_desc" : field descriptor implementation */
static const TMsgBuf_fieldDescriptor g_Rpcctrl_RpcServiceDescSetOutMsg_methodsDescriptor[1] =
{
  {
    "serviceDesc",                                                    /* field: * pName */
    MSGBUF_FIELDTYPE_MESSAGE,                                         /* field:   type */
    MSGBUF_TAGLABEL_REPEATED,                                         /* field:   label */
    0,                                                                /* field:   packed */
    1,                                                                /* field:   id */
    sizeof(TRpcctrl_RpcServiceDescriptor*),                           /* field:   sizeof_field */
    MSGBUF_OFFSET_OF(TRpcctrl_RpcServiceDescSetOutMsg,n_serviceDesc), /* field:   qoffset */
    MSGBUF_OFFSET_OF(TRpcctrl_RpcServiceDescSetOutMsg,serviceDesc),   /* field:   offset */
    &g_Rpcctrl_RpcServiceDescriptor_messageDescriptor,                /* field: * pDescriptor */
    NULL                                                              /* field: * pDefaultValue */
  }
};

/* "g_Rpcctrl_RpcServiceDescSetOutMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Rpcctrl_RpcServiceDescSetOutMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,                    /* field:   magicId */
  "Rpcctrl_RpcServiceDescSetOutMsg",                     /* field: * pName */
  "RpcServiceDescSetOutMsg",                             /* field: * pShortName */
  "Rpcctrl_RpcServiceDescSetOutMsg",                     /* field: * c_name */
  "rpcctrl",                                             /* field: * pPackageName */
  sizeof(TRpcctrl_RpcServiceDescSetOutMsg),              /* field:   sizeof_message */
  &g_rpcServiceDescSet_outMsg_default_value,             /* field:   init value */
  1,                                                     /* field:   n_fields */
  g_Rpcctrl_RpcServiceDescSetOutMsg_methodsDescriptor,   /* field: * pFields */
  &msgbuf_genericMessageInit,                            /* field:   message_init */
};

/* "g_Rpcctrl_EmptyMsg_messageDescriptor_field_desc" : message descriptor implementation */
const TMsgBuf_messageDescriptor g_Rpcctrl_EmptyMsg_messageDescriptor =
{
  MSGBUF_MESSAGE_DESCRIPTOR_MAGIC_ID,     /* field:   magicId */
  "Rpcctrl_EmptyMsg",                     /* field: * pName */
  "EmptyMsg",                             /* field: * pShortName */
  "Rpcctrl_EmptyMsg",                     /* field: * c_name */
  "rpcctrl",                              /* field: * pPackageName */
  sizeof(TRpcctrl_EmptyMsg),              /* field:   sizeof_message */
  &g_empty_msg_default_value,             /* field:   init value */
  0,                                      /* field:   n_fields */
  NULL,                                   /* field: * pFields */
  &msgbuf_genericMessageInit,             /* field:   message_init */
};


/*****************************************************************************
 * message init implementation                                               *
 ****************************************************************************/

/* init_Rpcctrl_RpcServiceDescriptor function implementation */
void init_Rpcctrl_RpcServiceDescriptor ( TRpcctrl_RpcServiceDescriptor * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Rpcctrl_RpcServiceDescriptor_messageDescriptor); }

/* init_Rpcctrl_RpcServiceDescSetOutMsg function implementation */
void init_Rpcctrl_RpcServiceDescSetOutMsg ( TRpcctrl_RpcServiceDescSetOutMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Rpcctrl_RpcServiceDescSetOutMsg_messageDescriptor); }

/* init_Rpcctrl_EmptyMsg function implementation */
void init_Rpcctrl_EmptyMsg ( TRpcctrl_EmptyMsg * pxInstance )
  { msgbuf_genericMessageInit ((TMsgBuf_message*)pxInstance, &g_Rpcctrl_EmptyMsg_messageDescriptor); }


/*****************************************************************************
 * message alloc implementation                                              *
 ****************************************************************************/

/* pAlloc_Rpcctrl_RpcServiceDescriptor function implementation */
TRpcctrl_RpcServiceDescriptor * pAlloc_Rpcctrl_RpcServiceDescriptor ()
{
  TRpcctrl_RpcServiceDescriptor * pNewInstance;
  pNewInstance = (TRpcctrl_RpcServiceDescriptor*)MSGBUF_SYS_malloc(sizeof(TRpcctrl_RpcServiceDescriptor));
  init_Rpcctrl_RpcServiceDescriptor (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Rpcctrl_RpcServiceDescSetOutMsg function implementation */
TRpcctrl_RpcServiceDescSetOutMsg * pAlloc_Rpcctrl_RpcServiceDescSetOutMsg ()
{
  TRpcctrl_RpcServiceDescSetOutMsg * pNewInstance;
  pNewInstance = (TRpcctrl_RpcServiceDescSetOutMsg*)MSGBUF_SYS_malloc(sizeof(TRpcctrl_RpcServiceDescSetOutMsg));
  init_Rpcctrl_RpcServiceDescSetOutMsg (pNewInstance);
  return pNewInstance;
}

/* pAlloc_Rpcctrl_EmptyMsg function implementation */
TRpcctrl_EmptyMsg * pAlloc_Rpcctrl_EmptyMsg ()
{
  TRpcctrl_EmptyMsg * pNewInstance;
  pNewInstance = (TRpcctrl_EmptyMsg*)MSGBUF_SYS_malloc(sizeof(TRpcctrl_EmptyMsg));
  init_Rpcctrl_EmptyMsg (pNewInstance);
  return pNewInstance;
}


/*****************************************************************************
 * message dealloc implementation                                            *
 ****************************************************************************/

/* dealloc_Rpcctrl_RpcServiceDescriptor function implementation */
void dealloc_Rpcctrl_RpcServiceDescriptor (TRpcctrl_RpcServiceDescriptor * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Rpcctrl_RpcServiceDescSetOutMsg function implementation */
void dealloc_Rpcctrl_RpcServiceDescSetOutMsg (TRpcctrl_RpcServiceDescSetOutMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }

/* dealloc_Rpcctrl_EmptyMsg function implementation */
void dealloc_Rpcctrl_EmptyMsg (TRpcctrl_EmptyMsg * pxInstance)
  { msgbuf_genericMessageDeallocate ((TMsgBuf_message*)pxInstance); }


/*****************************************************************************
 * msgbuf enum test function implementation                                  *
 ****************************************************************************/


/*****************************************************************************
 * service descriptor implementation                                         *
 ****************************************************************************/

static const TMsgBuf_methodDescriptor g_rpcctrl_v1_0_1_serviceMethodsDescriptor[2] =
{
  /* 'hc_getServiceDescSet' method descriptor (index=0) */
  {
    "hc_getServiceDescSet",
    &g_Rpcctrl_EmptyMsg_messageDescriptor,
    &g_Rpcctrl_RpcServiceDescSetOutMsg_messageDescriptor,
    (TMsgBuf_rpcFctEntry)&rpc_rpcctrl_hc_getServiceDescSet
  },
  /* 'hc_resync' method descriptor (index=1) */
  {
    "hc_resync",
    &g_Rpcctrl_EmptyMsg_messageDescriptor,
    &g_Rpcctrl_EmptyMsg_messageDescriptor,
    (TMsgBuf_rpcFctEntry)&rpc_rpcctrl_hc_resync
  }
};

const TMsgBuf_serviceDescriptor g_rpcctrl_v1_0_1_serviceDescriptor =
{
  MSGBUF_SERVICE_DESCRIPTOR_MAGIC_ID,        /* field:   magic */
  "rpcctrl_v1_0_1",                          /* field: * pServiceName */
  "rpcctrl",                                 /* field: * pPackageName */
  0,                                         /* field:   methodId */
  2,                                         /* field:   n_methods */
  g_rpcctrl_v1_0_1_serviceMethodsDescriptor, /* field: * pMethods */
};

