/* DO NOT EDIT THIS FILE!!!
 * This file was automatically generated by msgbuf compiler!
 *
 * This file contains the msgbuf structure definitions associated
 * to the package rpcctrl.proto
 */

#ifndef _RPC_API_RPCCTRL_H_
#define _RPC_API_RPCCTRL_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*****************************************************************************
 * include files                                                             *
 ****************************************************************************/

#include "src/msgbuf_rpcctrl.h"


/* RPC method: rpc_rpcctrl_hc_getServiceDescSet
 *
 * This method stands as a synchronous function call.
 * Caller of this function only returns after completion of
 * its remote execution.
 */
TRpc_status rpc_rpcctrl_hc_getServiceDescSet (
  TMsgBuf_rpcHandler                  xRpcHandler,
  const TRpcctrl_EmptyMsg           * pxInputMessage,
  TRpcctrl_RpcServiceDescSetOutMsg ** pxOutputMessage );


/* RPC method: rpc_rpcctrl_hc_resync
 *
 * This method stands as a synchronous function call.
 * Caller of this function only returns after completion of
 * its remote execution.
 */
TRpc_status rpc_rpcctrl_hc_resync (
  TMsgBuf_rpcHandler         xRpcHandler,
  const TRpcctrl_EmptyMsg  * pxInputMessage,
  TRpcctrl_EmptyMsg       ** pxOutputMessage );



#ifdef __cplusplus
}
#endif /* __cplusplus */


#endif /* _RPC_API_RPCCTRL_H_ */
