/* DO NOT EDIT THIS FILE!!!
 * This file was automatically generated by msgbuf compiler!
 *
 * This file contains the msgbuf structure definitions associated
 * to the package rpcctrl.proto
 */


/*****************************************************************************
 * include files                                                             *
 ****************************************************************************/

#include "inc/rpc_rpcctrl.h"
#include "src/rpc_rpcctrl_api.h"
#include "src/_msgbuf_rpcctrl.h"



/*****************************************************************************
 * RPC service remote API implementation                                     *
 ****************************************************************************/

